"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.inner
import local.my_domain_com.my_lib.input
import local.my_domain_com.my_lib.marker


class Middle(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.input.Input,
        local.my_domain_com.my_lib.destination.Destination,
        local.my_domain_com.my_lib.inner.Inner,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_position_action_inner__position_trigger_pos: literal.Position
        self.join_for_move_global_position_destination_to_global_position_input__global_position_marker: literal.Join
        self.join_for_empty_rule_global_position_destination: literal.Join
        self.join_for_empty_rule_global_position_input: literal.Join
        self.execution_action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ),
            self.scheduler,
        )
        self.execution_action_inner.join_for_move_global_position_input_to_global_position_destination = literal.NO_JOIN

    def accept_for_empty_rule_global_position_destination(self):
        if not self.join_for_empty_rule_global_position_destination.arrive():
            return
        self.move_global_position_destination_to_global_position_input__global_position_marker()

    def on_action_parent_occupied(self):
        self.create_action_inner__position_trigger_pos()

    def accept_for_empty_rule_global_position_input(self):
        if not self.join_for_empty_rule_global_position_input.arrive():
            return
        self.execution_action_inner.accept_for_empty_rule_global_position_input()

    def move_global_position_destination_to_global_position_input__global_position_marker(self):
        if not self.join_for_move_global_position_destination_to_global_position_input__global_position_marker.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.destination.Destination
        ).move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.input.Input
            ).particle.get_position(
                local.my_domain_com.my_lib.marker.Marker
            )
        )
        self.execution_action_inner.accept_for_empty_rule_global_position_input()

    def create_action_inner__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_inner__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_inner__position_trigger_pos.destroy_particle()
