"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.maker


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.maker.Maker,
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_maker: local.my_domain_com.my_lib.maker.MakerExecution
        self.execution_position_box__global_position_child__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.destruction_position_position_box__global_position_child: literal.Position
        self.destruction_position_position_box__action_maker__position_run: literal.Position
        self.join_for_destroy_position_box = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box",
            1,
        )
        self.execution_position_box__action_maker = local.my_domain_com.my_lib.maker.MakerExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.maker.Maker
            ),
            self.scheduler,
            self.trace_execution,
            "maker",
        )
        self.execution_position_box__action_maker.join_when_empty_global_position_child = literal.NO_JOIN
        self.execution_position_box__action_maker.join_for_move_position_temp_to_global_position_child = literal.NO_JOIN
        self.execution_position_box__action_maker.guarantees.global_position_child.inits.append(
            self.init_position_box__action_maker__global_position_child
        )
        self.execution_position_box__action_maker.guarantees.global_position_child.consumers.append(
            self.destroy_position_box__global_position_child
        )
        self.scheduler.submit(self.create_position_box__action_maker__position_run)
        self.execution_position_box__action_maker.on_action_parent_occupied()

    def create_position_box__action_maker__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box::/maker::run",
            1,
        )
        self.destruction_position_position_box__action_maker__position_run = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.maker.Maker
        ).get_interface_position(
            "position<run>"
        )
        self.scheduler.submit(self.destroy_position_box)
        self.destroy_position_box__action_maker__position_run()

    def destroy_position_box__global_position_child(self):
        self.destruction_position_position_box__global_position_child.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/child",
            1,
        )
        self.destroy_position_box()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box",
            1,
        )

    def destroy_position_box__action_maker__position_run(self):
        self.destruction_position_position_box__action_maker__position_run.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/maker::run",
            1,
        )

    def init_position_box__action_maker__global_position_child(self):
        self.destruction_position_position_box__global_position_child = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.execution_position_box__global_position_child__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
            self.trace_execution,
            "destructor",
        )
        self.execution_position_box__action_maker.guarantees.global_position_child.consumers.append(
            self.accept_guarantee_position_box__global_position_child__action_destructor
        )

    def accept_guarantee_position_box__global_position_child__action_destructor(self):
        self.execution_position_box__global_position_child__action_destructor.on_action_parent_occupied()
