"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.destruct
import local.my_domain_com.my_lib.marker_a
import local.my_domain_com.my_lib.marker_b
import local.my_domain_com.my_lib.maybe_empty


class Middle(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.marker_a.MarkerA,
                        local.my_domain_com.my_lib.marker_b.MarkerB,
                        local.my_domain_com.my_lib.maybe_empty.MaybeEmpty,
                        local.my_domain_com.my_lib.destruct.Destruct,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleGuarantees:
    def __init__(self):
        self.position_run = literal.Guarantee()


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = MiddleGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_holder_a = literal.LocalPosition(
            "position<holder_a>",
            scheduler=self.scheduler,
        )
        self.local_position_holder_b = literal.LocalPosition(
            "position<holder_b>",
            scheduler=self.scheduler,
        )
        self.execution_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_position_position_run__global_position_maybe_empty: literal.Position
        self.join_for_move_position_run__global_position_marker_a_to_position_holder_a: literal.Join
        self.join_for_move_position_run__global_position_marker_b_to_position_holder_b: literal.Join
        self.join_for_move_position_run_to_action_destroyer__position_run: literal.Join
        self.join_for_empty_rule_position_run__global_position_marker_a: literal.Join
        self.join_for_empty_rule_position_run__global_position_marker_b: literal.Join
        self.join_for_empty_rule_position_run: literal.Join
        self.execution_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=self.destruction_connections,
        )
        self.execution_action_destroyer.join_for_empty_rule_position_run__global_position_marker_a = literal.NO_JOIN
        self.execution_action_destroyer.join_for_empty_rule_position_run__global_position_marker_b = literal.NO_JOIN
        self.execution_action_destroyer.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_action_destroyer.join_for_move_position_run__global_position_marker_a_to_position_holder_a = literal.NO_JOIN
        self.execution_action_destroyer.join_for_move_position_run__global_position_marker_b_to_position_holder_b = literal.NO_JOIN
        self.execution_action_destroyer.join_for_destroy_position_run = self.scheduler.create_join(3)

    def accept_for_empty_rule_position_run__global_position_marker_a(self):
        if not self.join_for_empty_rule_position_run__global_position_marker_a.arrive():
            return
        self.move_position_run__global_position_marker_a_to_position_holder_a()

    def accept_for_empty_rule_position_run__global_position_marker_b(self):
        if not self.join_for_empty_rule_position_run__global_position_marker_b.arrive():
            return
        self.move_position_run__global_position_marker_b_to_position_holder_b()

    def accept_when_empty_position_run__global_position_maybe_empty(self):
        self.create_position_run__global_position_maybe_empty()

    def accept_for_empty_rule_position_run(self):
        if not self.join_for_empty_rule_position_run.arrive():
            return
        self.move_position_run_to_action_destroyer__position_run()

    def move_position_run__global_position_marker_a_to_position_holder_a(self):
        if not self.join_for_move_position_run__global_position_marker_a_to_position_holder_a.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_a.MarkerA
        ).move_particle_to(self.local_position_holder_a)
        self.local_position_holder_a.move_particle_to(
            self.action.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_a.MarkerA
            )
        )
        self.move_position_run_to_action_destroyer__position_run()

    def move_position_run__global_position_marker_b_to_position_holder_b(self):
        if not self.join_for_move_position_run__global_position_marker_b_to_position_holder_b.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_b.MarkerB
        ).move_particle_to(self.local_position_holder_b)
        self.local_position_holder_b.move_particle_to(
            self.action.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_b.MarkerB
            )
        )
        self.move_position_run_to_action_destroyer__position_run()

    def create_position_run__global_position_maybe_empty(self):
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.maybe_empty.MaybeEmpty
        ).create_particle()
        self.destruction_position_position_run__global_position_maybe_empty = self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.maybe_empty.MaybeEmpty
        )
        self.destruction_position_position_run__global_position_maybe_empty.destroy_particle()
        self.move_position_run_to_action_destroyer__position_run()

    def move_position_run_to_action_destroyer__position_run(self):
        if not self.join_for_move_position_run_to_action_destroyer__position_run.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.execution_action_destroyer.init_position_run__action_destruct()
        self.guarantees.position_run.publish(
            self.scheduler,
            self.execution_action_destroyer.accept_for_empty_rule_position_run__global_position_marker_a,
            self.execution_action_destroyer.accept_for_empty_rule_position_run__global_position_marker_b,
            self.execution_action_destroyer.accept_when_empty_position_run__global_position_maybe_empty,
        )
