"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.marker_a
import local.my_domain_com.my_lib.marker_b


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.marker_a.MarkerA,
                        local.my_domain_com.my_lib.marker_b.MarkerB,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.position_run = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_holder_a = literal.LocalPosition(
            "position<holder_a>",
            scheduler=self.scheduler,
        )
        self.local_position_holder_b = literal.LocalPosition(
            "position<holder_b>",
            scheduler=self.scheduler,
        )
        self.destruction_position_position_run__global_position_marker_a: literal.Position
        self.destruction_position_position_run__global_position_marker_b: literal.Position
        self.join_for_move_position_run__global_position_marker_a_to_position_holder_a: literal.Join
        self.join_for_move_position_run__global_position_marker_b_to_position_holder_b: literal.Join
        self.join_for_destroy_position_run: literal.Join
        self.join_for_empty_rule_position_run__global_position_marker_a: literal.Join
        self.join_for_empty_rule_position_run__global_position_marker_b: literal.Join
        self.join_for_empty_rule_position_run: literal.Join

    def accept_for_empty_rule_position_run__global_position_marker_a(self):
        if not self.join_for_empty_rule_position_run__global_position_marker_a.arrive():
            return
        self.move_position_run__global_position_marker_a_to_position_holder_a()

    def accept_for_empty_rule_position_run__global_position_marker_b(self):
        if not self.join_for_empty_rule_position_run__global_position_marker_b.arrive():
            return
        self.move_position_run__global_position_marker_b_to_position_holder_b()

    def accept_for_empty_rule_position_run(self):
        if not self.join_for_empty_rule_position_run.arrive():
            return
        self.destroy_position_run()

    def move_position_run__global_position_marker_a_to_position_holder_a(self):
        if not self.join_for_move_position_run__global_position_marker_a_to_position_holder_a.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_a.MarkerA
        ).move_particle_to(self.local_position_holder_a)
        self.scheduler.move_completed(
            self.trace_execution,
            "run::/marker_a",
            "holder_a",
            1,
        )
        self.local_position_holder_a.move_particle_to(
            self.action.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_a.MarkerA
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "holder_a",
            "run::/marker_a",
            1,
        )
        self.destruction_position_position_run__global_position_marker_a = self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_a.MarkerA
        )
        self.scheduler.submit(self.destroy_position_run)
        self.destroy_position_run__global_position_marker_a()

    def move_position_run__global_position_marker_b_to_position_holder_b(self):
        if not self.join_for_move_position_run__global_position_marker_b_to_position_holder_b.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_b.MarkerB
        ).move_particle_to(self.local_position_holder_b)
        self.scheduler.move_completed(
            self.trace_execution,
            "run::/marker_b",
            "holder_b",
            1,
        )
        self.local_position_holder_b.move_particle_to(
            self.action.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.marker_b.MarkerB
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "holder_b",
            "run::/marker_b",
            1,
        )
        self.destruction_position_position_run__global_position_marker_b = self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker_b.MarkerB
        )
        self.scheduler.submit(self.destroy_position_run)
        self.destroy_position_run__global_position_marker_b()

    def destroy_position_run(self):
        if not self.join_for_destroy_position_run.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_run)

    def continue_destroy_position_run(self):
        self.action.get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "run",
            1,
        )
        self.guarantees.position_run.publish(
            self.scheduler,
        )

    def destroy_position_run__global_position_marker_a(self):
        literal.continue_destruction(self.continue_destroy_position_run__global_position_marker_a)

    def continue_destroy_position_run__global_position_marker_a(self):
        self.destruction_position_position_run__global_position_marker_a.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "run::/marker_a",
            1,
        )

    def destroy_position_run__global_position_marker_b(self):
        literal.continue_destruction(self.continue_destroy_position_run__global_position_marker_b)

    def continue_destroy_position_run__global_position_marker_b(self):
        self.destruction_position_position_run__global_position_marker_b.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "run::/marker_b",
            1,
        )
