"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.end_dest
import local.my_domain_com.my_lib.end_local
import local.my_domain_com.my_lib.mid_dest
import local.my_domain_com.my_lib.mid_local


class Act(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<iface_dest>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<chain_dest>",
                    constraints=(
                        local.my_domain_com.my_lib.mid_dest.MidDest,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class ActGuarantees:
    def __init__(self):
        self.position_iface_dest = literal.Guarantee()
        self.position_chain_dest = literal.Guarantee()
        self.position_trigger = literal.Guarantee()


@final
class ActExecution:
    def __init__(
        self,
        action: Act,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = ActGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_src_a = literal.LocalPosition(
            "position<src_a>",
            scheduler=self.scheduler,
        )
        self.local_position_src_b = literal.LocalPosition(
            "position<src_b>",
            scheduler=self.scheduler,
        )
        self.local_position_src_c = literal.LocalPosition(
            "position<src_c>",
            scheduler=self.scheduler,
        )
        self.local_position_src_d = literal.LocalPosition(
            "position<src_d>",
            scheduler=self.scheduler,
        )
        self.local_position_local_dest = literal.LocalPosition(
            "position<local_dest>",
            scheduler=self.scheduler,
        )
        self.local_position_local_chain_dest = literal.LocalPosition(
            "position<local_chain_dest>",
            constraints=(
                local.my_domain_com.my_lib.mid_local.MidLocal,
            ),
            scheduler=self.scheduler,
        )
        self.destruction_position_position_chain_dest__global_position_mid_dest: literal.Position
        self.destruction_position_position_chain_dest__global_position_mid_dest__global_position_end_dest: literal.Position
        self.destruction_position_position_local_chain_dest__global_position_mid_local: literal.Position
        self.destruction_position_position_local_chain_dest__global_position_mid_local__global_position_end_local: literal.Position
        self.join_for_move_position_src_b_to_position_iface_dest: literal.Join
        self.join_for_move_position_src_c_to_position_chain_dest__global_position_mid_dest__global_position_end_dest: literal.Join
        self.join_for_move_position_src_d_to_position_local_chain_dest__global_position_mid_local__global_position_end_local = self.scheduler.create_join(2)
        self.join_for_destroy_position_chain_dest: literal.Join
        self.join_for_destroy_position_chain_dest__global_position_mid_dest: literal.Join
        self.join_for_destroy_position_trigger: literal.Join
        self.join_when_empty_position_iface_dest: literal.Join
        self.join_when_empty_position_chain_dest__global_position_mid_dest__global_position_end_dest: literal.Join
        self.join_for_empty_rule_position_chain_dest: literal.Join
        self.join_for_empty_rule_position_chain_dest__global_position_mid_dest: literal.Join
        self.join_for_empty_rule_position_trigger: literal.Join

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_src_a)
        self.scheduler.submit(self.create_position_src_b)
        self.scheduler.submit(self.create_position_src_c)
        self.scheduler.submit(self.create_position_src_d)
        self.create_position_local_chain_dest()

    def accept_when_empty_position_iface_dest(self):
        if not self.join_when_empty_position_iface_dest.arrive():
            return
        self.move_position_src_b_to_position_iface_dest()

    def accept_when_empty_position_chain_dest__global_position_mid_dest__global_position_end_dest(self):
        if not self.join_when_empty_position_chain_dest__global_position_mid_dest__global_position_end_dest.arrive():
            return
        self.move_position_src_c_to_position_chain_dest__global_position_mid_dest__global_position_end_dest()

    def accept_for_empty_rule_position_chain_dest(self):
        if not self.join_for_empty_rule_position_chain_dest.arrive():
            return
        self.destroy_position_chain_dest()

    def accept_for_empty_rule_position_chain_dest__global_position_mid_dest(self):
        if not self.join_for_empty_rule_position_chain_dest__global_position_mid_dest.arrive():
            return
        self.destroy_position_chain_dest__global_position_mid_dest()

    def accept_for_empty_rule_position_trigger(self):
        if not self.join_for_empty_rule_position_trigger.arrive():
            return
        self.destroy_position_trigger()

    def create_position_src_a(self):
        self.local_position_src_a.create_particle()
        self.local_position_src_a.move_particle_to(self.local_position_local_dest)
        self.local_position_local_dest.destroy_particle()

    def create_position_src_b(self):
        self.local_position_src_b.create_particle()
        self.move_position_src_b_to_position_iface_dest()

    def create_position_src_c(self):
        self.local_position_src_c.create_particle()
        self.move_position_src_c_to_position_chain_dest__global_position_mid_dest__global_position_end_dest()

    def create_position_src_d(self):
        self.local_position_src_d.create_particle()
        self.move_position_src_d_to_position_local_chain_dest__global_position_mid_local__global_position_end_local()

    def create_position_local_chain_dest(self):
        self.local_position_local_chain_dest.create_particle()
        self.local_position_local_chain_dest.particle.get_position(
            local.my_domain_com.my_lib.mid_local.MidLocal
        ).create_particle()
        self.move_position_src_d_to_position_local_chain_dest__global_position_mid_local__global_position_end_local()

    def move_position_src_b_to_position_iface_dest(self):
        if not self.join_for_move_position_src_b_to_position_iface_dest.arrive():
            return
        self.local_position_src_b.move_particle_to(
            self.action.get_interface_position(
                "position<iface_dest>"
            )
        )
        self.action.get_interface_position(
            "position<iface_dest>"
        ).destroy_particle()
        self.guarantees.position_iface_dest.publish(
            self.scheduler,
        )

    def move_position_src_c_to_position_chain_dest__global_position_mid_dest__global_position_end_dest(self):
        if not self.join_for_move_position_src_c_to_position_chain_dest__global_position_mid_dest__global_position_end_dest.arrive():
            return
        self.local_position_src_c.move_particle_to(
            self.action.get_interface_position(
                "position<chain_dest>"
            ).particle.get_position(
                local.my_domain_com.my_lib.mid_dest.MidDest
            ).particle.get_position(
                local.my_domain_com.my_lib.end_dest.EndDest
            )
        )
        self.destruction_position_position_chain_dest__global_position_mid_dest = self.action.get_interface_position(
            "position<chain_dest>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid_dest.MidDest
        )
        self.destruction_position_position_chain_dest__global_position_mid_dest__global_position_end_dest = self.action.get_interface_position(
            "position<chain_dest>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid_dest.MidDest
        ).particle.get_position(
            local.my_domain_com.my_lib.end_dest.EndDest
        )
        self.scheduler.submit(self.destroy_position_chain_dest)
        self.scheduler.submit(self.destroy_position_chain_dest__global_position_mid_dest)
        self.destroy_position_chain_dest__global_position_mid_dest__global_position_end_dest()

    def move_position_src_d_to_position_local_chain_dest__global_position_mid_local__global_position_end_local(self):
        if not self.join_for_move_position_src_d_to_position_local_chain_dest__global_position_mid_local__global_position_end_local.arrive():
            return
        self.local_position_src_d.move_particle_to(
            self.local_position_local_chain_dest.particle.get_position(
                local.my_domain_com.my_lib.mid_local.MidLocal
            ).particle.get_position(
                local.my_domain_com.my_lib.end_local.EndLocal
            )
        )
        self.destruction_position_position_local_chain_dest__global_position_mid_local = self.local_position_local_chain_dest.particle.get_position(
            local.my_domain_com.my_lib.mid_local.MidLocal
        )
        self.destruction_position_position_local_chain_dest__global_position_mid_local__global_position_end_local = self.local_position_local_chain_dest.particle.get_position(
            local.my_domain_com.my_lib.mid_local.MidLocal
        ).particle.get_position(
            local.my_domain_com.my_lib.end_local.EndLocal
        )
        self.scheduler.submit(self.destroy_position_local_chain_dest)
        self.scheduler.submit(self.destroy_position_local_chain_dest__global_position_mid_local)
        self.destroy_position_local_chain_dest__global_position_mid_local__global_position_end_local()

    def destroy_position_chain_dest(self):
        if not self.join_for_destroy_position_chain_dest.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_chain_dest)

    def continue_destroy_position_chain_dest(self):
        self.action.get_interface_position(
            "position<chain_dest>"
        ).destroy_particle()
        self.guarantees.position_chain_dest.publish(
            self.scheduler,
        )

    def destroy_position_chain_dest__global_position_mid_dest(self):
        if not self.join_for_destroy_position_chain_dest__global_position_mid_dest.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_chain_dest__global_position_mid_dest)

    def continue_destroy_position_chain_dest__global_position_mid_dest(self):
        self.destruction_position_position_chain_dest__global_position_mid_dest.destroy_particle()

    def destroy_position_chain_dest__global_position_mid_dest__global_position_end_dest(self):
        literal.continue_destruction(self.continue_destroy_position_chain_dest__global_position_mid_dest__global_position_end_dest)

    def continue_destroy_position_chain_dest__global_position_mid_dest__global_position_end_dest(self):
        self.destruction_position_position_chain_dest__global_position_mid_dest__global_position_end_dest.destroy_particle()

    def destroy_position_trigger(self):
        if not self.join_for_destroy_position_trigger.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_trigger)

    def continue_destroy_position_trigger(self):
        self.action.get_interface_position(
            "position<trigger>"
        ).destroy_particle()
        self.guarantees.position_trigger.publish(
            self.scheduler,
        )

    def destroy_position_local_chain_dest(self):
        self.local_position_local_chain_dest.destroy_particle()

    def destroy_position_local_chain_dest__global_position_mid_local(self):
        self.destruction_position_position_local_chain_dest__global_position_mid_local.destroy_particle()

    def destroy_position_local_chain_dest__global_position_mid_local__global_position_end_local(self):
        self.destruction_position_position_local_chain_dest__global_position_mid_local__global_position_end_local.destroy_particle()
