"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.item
import local.my_domain_com.my_lib.other


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.other.Other,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.item.Item,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_destination = literal.LocalPosition(
            "position<destination>",
            scheduler=self.scheduler,
        )
        self.execution_position_gateway__action_other: local.my_domain_com.my_lib.other.OtherExecution
        self.destruction_position_position_gateway__action_other__position_destination: literal.Position
        self.join_for_move_position_destination_to_position_gateway__action_other__position_box = self.scheduler.create_join(2)
        self.join_for_destroy_position_gateway = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_gateway)
        self.create_position_box()

    def create_position_gateway(self):
        self.local_position_gateway.create_particle()
        self.execution_position_gateway__action_other = local.my_domain_com.my_lib.other.OtherExecution(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.other.Other
            ),
            self.scheduler,
        )
        self.execution_position_gateway__action_other.join_when_empty_position_destination = literal.NO_JOIN
        self.execution_position_gateway__action_other.join_for_empty_rule_position_box = literal.NO_JOIN
        self.execution_position_gateway__action_other.join_for_move_position_box__global_position_item_to_position_destination = literal.NO_JOIN
        self.execution_position_gateway__action_other.join_for_destroy_position_box = literal.NO_JOIN
        self.execution_position_gateway__action_other.guarantees.position_destination.inits.append(
            self.init_position_gateway__action_other__position_destination
        )
        self.execution_position_gateway__action_other.guarantees.position_destination.consumers.append(
            self.destroy_position_gateway__action_other__position_destination
        )
        self.execution_position_gateway__action_other.guarantees.position_box.consumers.append(
            self.destroy_position_gateway
        )
        self.move_position_destination_to_position_gateway__action_other__position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.local_position_box.move_particle_to(self.local_position_destination)
        self.move_position_destination_to_position_gateway__action_other__position_box()

    def move_position_destination_to_position_gateway__action_other__position_box(self):
        if not self.join_for_move_position_destination_to_position_gateway__action_other__position_box.arrive():
            return
        self.local_position_destination.move_particle_to(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.other.Other
            ).get_interface_position(
                "position<box>"
            )
        )
        self.execution_position_gateway__action_other.accept_when_empty_position_box__global_position_item()

    def destroy_position_gateway__action_other__position_destination(self):
        self.destruction_position_position_gateway__action_other__position_destination.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway(self):
        if not self.join_for_destroy_position_gateway.arrive():
            return
        self.local_position_gateway.destroy_particle()

    def init_position_gateway__action_other__position_destination(self):
        self.destruction_position_position_gateway__action_other__position_destination = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<destination>"
        )
