"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.input
import local.my_domain_com.my_lib.other


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.input.Input,
        local.my_domain_com.my_lib.other.Other,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.execution_action_other.join_for_empty_rule_global_position_input__global_position_a = scheduler.create_join(2)
        execution.execution_action_other.join_when_empty_position_holder_b = literal.NO_JOIN
        execution.execution_action_other.join_when_empty_position_holder_c = literal.NO_JOIN
        execution.execution_action_other.join_for_move_position_holder_a_to_position_holder_b = scheduler.create_join(2)
        execution.execution_action_other.join_for_move_global_position_input__global_position_a_to_position_holder_c = scheduler.create_join(2)
        execution.join_when_empty_action_other__position_holder_a = literal.NO_JOIN
        execution.join_when_empty_action_other__position_holder_b = literal.NO_JOIN
        execution.join_when_empty_action_other__position_holder_c = literal.NO_JOIN
        scheduler.submit(execution.accept_when_empty_global_position_input)
        scheduler.submit(execution.on_action_parent_occupied)
        scheduler.submit(execution.accept_when_empty_action_other__position_holder_a)
        scheduler.submit(execution.accept_when_empty_action_other__position_holder_b)
        execution.accept_when_empty_action_other__position_holder_c()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_other: local.my_domain_com.my_lib.other.OtherExecution
        self.destruction_position_action_other__position_trigger_pos: literal.Position
        self.join_when_empty_action_other__position_holder_a: literal.Join
        self.join_when_empty_action_other__position_holder_b: literal.Join
        self.join_when_empty_action_other__position_holder_c: literal.Join
        self.execution_action_other = local.my_domain_com.my_lib.other.OtherExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.other.Other
            ),
            self.scheduler,
        )
        self.execution_action_other.join_for_empty_rule_global_position_input = literal.NO_JOIN
        self.execution_action_other.join_for_move_global_position_input__global_position_a_to_position_holder_a = literal.NO_JOIN
        self.execution_action_other.join_for_destroy_global_position_input = literal.NO_JOIN

    def accept_when_empty_global_position_input(self):
        self.create_global_position_input()

    def on_action_parent_occupied(self):
        self.create_action_other__position_trigger_pos()

    def accept_when_empty_action_other__position_holder_a(self):
        if not self.join_when_empty_action_other__position_holder_a.arrive():
            return
        self.execution_action_other.accept_for_empty_rule_global_position_input__global_position_a()

    def accept_when_empty_action_other__position_holder_b(self):
        if not self.join_when_empty_action_other__position_holder_b.arrive():
            return
        self.execution_action_other.accept_when_empty_position_holder_b()

    def accept_when_empty_action_other__position_holder_c(self):
        if not self.join_when_empty_action_other__position_holder_c.arrive():
            return
        self.execution_action_other.accept_when_empty_position_holder_c()

    def create_global_position_input(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).create_particle()
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.execution_action_other.accept_for_empty_rule_global_position_input__global_position_a()

    def create_action_other__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_other__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_other__position_trigger_pos.destroy_particle()
