"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.inner
import local.my_domain_com.my_lib.parent


class Middle(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<iface>",
                    constraints=(
                        local.my_domain_com.my_lib.parent.Parent,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleGuarantees:
    def __init__(self):
        self.position_iface = literal.Guarantee()


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = MiddleGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_gw = literal.LocalPosition(
            "position<gw>",
            constraints=(
                local.my_domain_com.my_lib.inner.Inner,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_gw__action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_position_position_gw__action_inner__position_run: literal.Position
        self.destruction_position_position_gw__action_inner__position_input: literal.Position
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent: literal.Position
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent__global_position_a: literal.Position
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent__global_position_b: literal.Position
        self.join_for_move_position_iface_to_position_gw__action_inner__position_input: literal.Join
        self.join_for_destroy_position_gw = self.scheduler.create_join(3)
        self.join_for_destroy_position_gw__action_inner__position_input = self.scheduler.create_join(2)
        self.join_for_destroy_position_gw__action_inner__position_input__global_position_parent = self.scheduler.create_join(2)
        self.join_for_empty_rule_position_iface: literal.Join

    def on_action_parent_occupied(self):
        self.create_position_gw()

    def accept_for_empty_rule_position_iface(self):
        if not self.join_for_empty_rule_position_iface.arrive():
            return
        self.move_position_iface_to_position_gw__action_inner__position_input()

    def create_position_gw(self):
        self.local_position_gw.create_particle()
        self.execution_position_gw__action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.local_position_gw.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ),
            self.scheduler,
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_a.inits.append(
            self.init_position_gw__action_inner__position_input__global_position_parent__global_position_a
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_a.consumers.append(
            self.destroy_position_gw
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_a.consumers.append(
            self.destroy_position_gw__action_inner__position_input
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_a.consumers.append(
            self.destroy_position_gw__action_inner__position_input__global_position_parent
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_a.consumers.append(
            self.destroy_position_gw__action_inner__position_input__global_position_parent__global_position_a
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_b.inits.append(
            self.init_position_gw__action_inner__position_input__global_position_parent__global_position_b
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_b.consumers.append(
            self.destroy_position_gw
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_b.consumers.append(
            self.destroy_position_gw__action_inner__position_input
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_b.consumers.append(
            self.destroy_position_gw__action_inner__position_input__global_position_parent
        )
        self.execution_position_gw__action_inner.guarantees.position_input__global_position_parent__global_position_b.consumers.append(
            self.destroy_position_gw__action_inner__position_input__global_position_parent__global_position_b
        )
        self.scheduler.submit(self.move_position_iface_to_position_gw__action_inner__position_input)
        self.create_position_gw__action_inner__position_run()

    def move_position_iface_to_position_gw__action_inner__position_input(self):
        if not self.join_for_move_position_iface_to_position_gw__action_inner__position_input.arrive():
            return
        self.action.get_interface_position(
            "position<iface>"
        ).move_particle_to(
            self.local_position_gw.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<input>"
            )
        )
        self.guarantees.position_iface.publish(
            self.scheduler,
            self.execution_position_gw__action_inner.accept_when_empty_position_input__global_position_parent__global_position_a,
            self.execution_position_gw__action_inner.accept_when_empty_position_input__global_position_parent__global_position_b,
        )

    def create_position_gw__action_inner__position_run(self):
        self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_position_position_gw__action_inner__position_run = self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<run>"
        )
        self.scheduler.submit(self.destroy_position_gw)
        self.destroy_position_gw__action_inner__position_run()

    def destroy_position_gw(self):
        if not self.join_for_destroy_position_gw.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_gw)

    def continue_destroy_position_gw(self):
        self.local_position_gw.destroy_particle()

    def destroy_position_gw__action_inner__position_run(self):
        literal.continue_destruction(self.continue_destroy_position_gw__action_inner__position_run)

    def continue_destroy_position_gw__action_inner__position_run(self):
        self.destruction_position_position_gw__action_inner__position_run.destroy_particle()

    def destroy_position_gw__action_inner__position_input(self):
        if not self.join_for_destroy_position_gw__action_inner__position_input.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_gw__action_inner__position_input)

    def continue_destroy_position_gw__action_inner__position_input(self):
        self.destruction_position_position_gw__action_inner__position_input.destroy_particle()

    def destroy_position_gw__action_inner__position_input__global_position_parent(self):
        if not self.join_for_destroy_position_gw__action_inner__position_input__global_position_parent.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_gw__action_inner__position_input__global_position_parent)

    def continue_destroy_position_gw__action_inner__position_input__global_position_parent(self):
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent.destroy_particle()

    def destroy_position_gw__action_inner__position_input__global_position_parent__global_position_a(self):
        literal.continue_destruction(self.continue_destroy_position_gw__action_inner__position_input__global_position_parent__global_position_a)

    def continue_destroy_position_gw__action_inner__position_input__global_position_parent__global_position_a(self):
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent__global_position_a.destroy_particle()

    def destroy_position_gw__action_inner__position_input__global_position_parent__global_position_b(self):
        literal.continue_destruction(self.continue_destroy_position_gw__action_inner__position_input__global_position_parent__global_position_b)

    def continue_destroy_position_gw__action_inner__position_input__global_position_parent__global_position_b(self):
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent__global_position_b.destroy_particle()

    def init_position_gw__action_inner__position_input__global_position_parent__global_position_a(self):
        self.destruction_position_position_gw__action_inner__position_input = self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        )
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent = self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        )
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent__global_position_a = self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        )

    def init_position_gw__action_inner__position_input__global_position_parent__global_position_b(self):
        self.destruction_position_position_gw__action_inner__position_input__global_position_parent__global_position_b = self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        )
