"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.left
import local.my_domain_com.my_lib.right


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<target>",
                    constraints=(
                        local.my_domain_com.my_lib.left.Left,
                        local.my_domain_com.my_lib.right.Right,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.position_target = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_left_holder = literal.LocalPosition(
            "position<left_holder>",
            scheduler=self.scheduler,
        )
        self.local_position_right_holder = literal.LocalPosition(
            "position<right_holder>",
            scheduler=self.scheduler,
        )
        self.destruction_position_position_target__global_position_left: literal.Position
        self.destruction_position_position_target__global_position_right: literal.Position
        self.join_for_move_position_target__global_position_left_to_position_left_holder: literal.Join
        self.join_for_move_position_target__global_position_right_to_position_right_holder: literal.Join
        self.join_for_destroy_position_target: literal.Join
        self.join_for_empty_rule_position_target__global_position_left: literal.Join
        self.join_for_empty_rule_position_target__global_position_right: literal.Join
        self.join_for_empty_rule_position_target: literal.Join

    def accept_for_empty_rule_position_target__global_position_left(self):
        if not self.join_for_empty_rule_position_target__global_position_left.arrive():
            return
        self.move_position_target__global_position_left_to_position_left_holder()

    def accept_for_empty_rule_position_target__global_position_right(self):
        if not self.join_for_empty_rule_position_target__global_position_right.arrive():
            return
        self.move_position_target__global_position_right_to_position_right_holder()

    def accept_for_empty_rule_position_target(self):
        if not self.join_for_empty_rule_position_target.arrive():
            return
        self.destroy_position_target()

    def move_position_target__global_position_left_to_position_left_holder(self):
        if not self.join_for_move_position_target__global_position_left_to_position_left_holder.arrive():
            return
        self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.left.Left
        ).move_particle_to(self.local_position_left_holder)
        self.local_position_left_holder.move_particle_to(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_position(
                local.my_domain_com.my_lib.left.Left
            )
        )
        self.destruction_position_position_target__global_position_left = self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.left.Left
        )
        self.scheduler.submit(self.destroy_position_target)
        self.destroy_position_target__global_position_left()

    def move_position_target__global_position_right_to_position_right_holder(self):
        if not self.join_for_move_position_target__global_position_right_to_position_right_holder.arrive():
            return
        self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.right.Right
        ).move_particle_to(self.local_position_right_holder)
        self.local_position_right_holder.move_particle_to(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_position(
                local.my_domain_com.my_lib.right.Right
            )
        )
        self.destruction_position_position_target__global_position_right = self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.right.Right
        )
        self.scheduler.submit(self.destroy_position_target)
        self.destroy_position_target__global_position_right()

    def destroy_position_target(self):
        if not self.join_for_destroy_position_target.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_target)

    def continue_destroy_position_target(self):
        self.action.get_interface_position(
            "position<target>"
        ).destroy_particle()
        self.guarantees.position_target.publish(
            self.scheduler,
        )

    def destroy_position_target__global_position_left(self):
        literal.continue_destruction(self.continue_destroy_position_target__global_position_left)

    def continue_destroy_position_target__global_position_left(self):
        self.destruction_position_position_target__global_position_left.destroy_particle()

    def destroy_position_target__global_position_right(self):
        literal.continue_destruction(self.continue_destroy_position_target__global_position_right)

    def continue_destroy_position_target__global_position_right(self):
        self.destruction_position_position_target__global_position_right.destroy_particle()
