"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.mover


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_parent = literal.LocalPosition(
            "position<parent>",
            constraints=(
                local.my_domain_com.my_lib.mover.Mover,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_parent__action_mover: local.my_domain_com.my_lib.mover.MoverExecution
        self.destruction_position_position_parent__action_mover__position_destination: literal.Position
        self.join_for_destroy_position_parent = self.scheduler.create_join(3)

    def on_action_parent_occupied(self):
        self.create_position_parent()

    def create_position_parent(self):
        self.local_position_parent.create_particle()
        self.execution_position_parent__action_mover = local.my_domain_com.my_lib.mover.MoverExecution(
            self.local_position_parent.particle.get_action(
                local.my_domain_com.my_lib.mover.Mover
            ),
            self.scheduler,
        )
        self.execution_position_parent__action_mover.join_for_empty_rule_position_source = literal.NO_JOIN
        self.execution_position_parent__action_mover.join_when_empty_position_destination = literal.NO_JOIN
        self.execution_position_parent__action_mover.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_position_parent__action_mover.join_for_move_position_source_to_position_intermediate = literal.NO_JOIN
        self.execution_position_parent__action_mover.join_for_move_position_intermediate_to_position_destination = literal.NO_JOIN
        self.execution_position_parent__action_mover.join_for_destroy_position_run = literal.NO_JOIN
        self.execution_position_parent__action_mover.guarantees.position_destination.inits.append(
            self.init_position_parent__action_mover__position_destination
        )
        self.execution_position_parent__action_mover.guarantees.position_destination.consumers.append(
            self.destroy_position_parent__action_mover__position_destination
        )
        self.execution_position_parent__action_mover.guarantees.position_source.consumers.append(
            self.destroy_position_parent
        )
        self.execution_position_parent__action_mover.guarantees.position_run.consumers.append(
            self.destroy_position_parent
        )
        self.scheduler.submit(self.create_position_parent__action_mover__position_source)
        self.create_position_parent__action_mover__position_run()

    def create_position_parent__action_mover__position_source(self):
        self.local_position_parent.particle.get_action(
            local.my_domain_com.my_lib.mover.Mover
        ).get_interface_position(
            "position<source>"
        ).create_particle()
        self.execution_position_parent__action_mover.accept_for_empty_rule_position_source()

    def create_position_parent__action_mover__position_run(self):
        self.local_position_parent.particle.get_action(
            local.my_domain_com.my_lib.mover.Mover
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.execution_position_parent__action_mover.accept_for_empty_rule_position_run()

    def destroy_position_parent__action_mover__position_destination(self):
        self.destruction_position_position_parent__action_mover__position_destination.destroy_particle()
        self.destroy_position_parent()

    def destroy_position_parent(self):
        if not self.join_for_destroy_position_parent.arrive():
            return
        self.local_position_parent.destroy_particle()

    def init_position_parent__action_mover__position_destination(self):
        self.destruction_position_position_parent__action_mover__position_destination = self.local_position_parent.particle.get_action(
            local.my_domain_com.my_lib.mover.Mover
        ).get_interface_position(
            "position<destination>"
        )
