"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.a.A,
                local.my_domain_com.my_lib.b.B,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_destination = literal.LocalPosition(
            "position<destination>",
            scheduler=self.scheduler,
        )
        self.destruction_position_position_destination__global_position_a: literal.Position
        self.destruction_position_position_destination__global_position_b: literal.Position
        self.join_for_move_position_source_to_position_destination = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_source()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.scheduler.submit(self.create_position_source__global_position_a)
        self.create_position_source__global_position_b()

    def create_position_source__global_position_a(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.move_position_source_to_position_destination()

    def create_position_source__global_position_b(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).create_particle()
        self.move_position_source_to_position_destination()

    def move_position_source_to_position_destination(self):
        if not self.join_for_move_position_source_to_position_destination.arrive():
            return
        self.local_position_source.move_particle_to(self.local_position_destination)
        self.destruction_position_position_destination__global_position_a = self.local_position_destination.particle.get_position(
            local.my_domain_com.my_lib.a.A
        )
        self.destruction_position_position_destination__global_position_b = self.local_position_destination.particle.get_position(
            local.my_domain_com.my_lib.b.B
        )
        self.scheduler.submit(self.destroy_position_destination)
        self.scheduler.submit(self.destroy_position_destination__global_position_a)
        self.destroy_position_destination__global_position_b()

    def destroy_position_destination(self):
        self.local_position_destination.destroy_particle()

    def destroy_position_destination__global_position_a(self):
        self.destruction_position_position_destination__global_position_a.destroy_particle()

    def destroy_position_destination__global_position_b(self):
        self.destruction_position_position_destination__global_position_b.destroy_particle()
