"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.forwarder
import local.my_domain_com.my_lib.implied


class Destructor(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.forwarder.Forwarder,
        local.my_domain_com.my_lib.implied.Implied,
    )


@final
class DestructorGuarantees:
    def __init__(self):
        self.global_position_implied = literal.Guarantee()


@final
class DestructorExecution:
    def __init__(
        self,
        action: Destructor,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = DestructorGuarantees()
        self.execution_action_forwarder: local.my_domain_com.my_lib.forwarder.ForwarderExecution
        self.execution_action_forwarder = local.my_domain_com.my_lib.forwarder.ForwarderExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.forwarder.Forwarder
            ),
            self.scheduler,
            self.trace_execution,
            "forwarder",
        )
        self.execution_action_forwarder.join_for_empty_rule_position_trigger_pos = literal.NO_JOIN
        self.execution_action_forwarder.join_for_destroy_position_trigger_pos = literal.NO_JOIN
        self.execution_action_forwarder.execution_action_filler.guarantees.global_position_implied.consumers.append(
            self.create_global_position_implied
        )

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_forwarder__position_trigger_pos)
        self.execution_action_forwarder.on_action_parent_occupied()

    def accept_when_empty_global_position_implied(self):
        self.execution_action_forwarder.accept_when_empty_global_position_implied()

    def create_action_forwarder__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.forwarder.Forwarder
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/forwarder::trigger_pos",
            1,
        )
        self.execution_action_forwarder.accept_for_empty_rule_position_trigger_pos()

    def create_global_position_implied(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.implied.Implied
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/implied",
            1,
        )
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.implied.Implied
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/implied",
            1,
        )
        self.guarantees.global_position_implied.publish(
            self.scheduler,
        )
