"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.destruction_position_position_box__global_position_child: literal.Position
        self.destruction_position_position_box__global_position_child_2: literal.Position
        self.join_for_move_position_source_to_position_box = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_box)
        self.create_position_source()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.destruction_position_position_box__global_position_child = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.destruction_position_position_box__global_position_child.destroy_particle()
        self.local_position_box.destroy_particle()
        self.move_position_source_to_position_box()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.move_position_source_to_position_box()

    def move_position_source_to_position_box(self):
        if not self.join_for_move_position_source_to_position_box.arrive():
            return
        self.local_position_source.move_particle_to(self.local_position_box)
        self.destruction_position_position_box__global_position_child_2 = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.destruction_position_position_box__global_position_child_2.destroy_particle()
        self.local_position_box.destroy_particle()
