"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.item


class Inner(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<input>",
                    constraints=(
                        local.my_domain_com.my_lib.item.Item,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class InnerGuarantees:
    def __init__(self):
        self.position_input__global_position_item = literal.Guarantee()


@final
class InnerExecution:
    def __init__(
        self,
        action: Inner,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = InnerGuarantees()
        self.destruction_connections = destruction_connections
        self.destruction_position_position_input__global_position_item: literal.Position
        self.join_for_destroy_position_input__global_position_item: literal.Join
        self.join_for_empty_rule_position_input__global_position_item: literal.Join

    def accept_for_empty_rule_position_input__global_position_item(self):
        if not self.join_for_empty_rule_position_input__global_position_item.arrive():
            return
        self.destruction_position_position_input__global_position_item = self.action.get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.item.Item
        )
        self.destroy_position_input__global_position_item()

    def destroy_position_input__global_position_item(self):
        if not self.join_for_destroy_position_input__global_position_item.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_input__global_position_item)

    def continue_destroy_position_input__global_position_item(self):
        self.destruction_position_position_input__global_position_item.destroy_particle()
        self.guarantees.position_input__global_position_item.publish(
            self.scheduler,
        )
