"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.middle


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.execution_position_box__global_position_child__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.destruction_position_position_box__global_position_child: literal.Position
        self.destruction_position_position_box__action_middle__position_run: literal.Position
        self.join_for_destroy_position_box = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
        )
        self.execution_position_box__action_middle.execution_action_inner.guarantees.global_position_child.inits.append(
            self.init_position_box__action_middle__action_inner__global_position_child
        )
        self.execution_position_box__action_middle.execution_action_inner.guarantees.global_position_child.consumers.append(
            self.destroy_position_box__global_position_child
        )
        self.scheduler.submit(self.create_position_box__action_middle__position_run)
        self.scheduler.submit(self.execution_position_box__action_middle.on_action_parent_occupied)
        self.execution_position_box__action_middle.accept_when_empty_global_position_child()

    def create_position_box__action_middle__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_position_position_box__action_middle__position_run = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<run>"
        )
        self.scheduler.submit(self.destroy_position_box)
        self.destroy_position_box__action_middle__position_run()

    def destroy_position_box__global_position_child(self):
        self.destruction_position_position_box__global_position_child.destroy_particle()
        self.destroy_position_box()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()

    def destroy_position_box__action_middle__position_run(self):
        self.destruction_position_position_box__action_middle__position_run.destroy_particle()

    def init_position_box__action_middle__action_inner__global_position_child(self):
        self.destruction_position_position_box__global_position_child = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.execution_position_box__global_position_child__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
        )
        self.execution_position_box__action_middle.execution_action_inner.guarantees.global_position_child.consumers.append(
            self.accept_guarantee_position_box__global_position_child__action_destructor
        )

    def accept_guarantee_position_box__global_position_child__action_destructor(self):
        self.execution_position_box__global_position_child__action_destructor.on_action_parent_occupied()
