"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destruct
import local.my_domain_com.my_lib.marker_a
import local.my_domain_com.my_lib.marker_b
import local.my_domain_com.my_lib.maybe_empty
import local.my_domain_com.my_lib.middle


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.middle.Middle,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.marker_a.MarkerA,
                local.my_domain_com.my_lib.marker_b.MarkerB,
                local.my_domain_com.my_lib.maybe_empty.MaybeEmpty,
                local.my_domain_com.my_lib.destruct.Destruct,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_position_position_source__global_position_maybe_empty: literal.Position
        self.join_for_move_position_source_to_action_middle__position_run = self.scheduler.create_join(3)
        self.execution_action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
        )
        self.execution_action_middle.join_for_empty_rule_position_run__global_position_marker_a = literal.NO_JOIN
        self.execution_action_middle.join_for_empty_rule_position_run__global_position_marker_b = literal.NO_JOIN
        self.execution_action_middle.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_action_middle.join_for_move_position_run__global_position_marker_a_to_position_holder_a = literal.NO_JOIN
        self.execution_action_middle.join_for_move_position_run__global_position_marker_b_to_position_holder_b = literal.NO_JOIN
        self.execution_action_middle.join_for_move_position_run_to_action_destroyer__position_run = self.scheduler.create_join(3)

    def on_action_parent_occupied(self):
        self.create_position_source()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.scheduler.submit(self.create_position_source__global_position_marker_a)
        self.scheduler.submit(self.create_position_source__global_position_marker_b)
        self.create_position_source__global_position_maybe_empty()

    def create_position_source__global_position_marker_a(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.marker_a.MarkerA
        ).create_particle()
        self.move_position_source_to_action_middle__position_run()

    def create_position_source__global_position_marker_b(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.marker_b.MarkerB
        ).create_particle()
        self.move_position_source_to_action_middle__position_run()

    def create_position_source__global_position_maybe_empty(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.maybe_empty.MaybeEmpty
        ).create_particle()
        self.destruction_position_position_source__global_position_maybe_empty = self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.maybe_empty.MaybeEmpty
        )
        self.destruction_position_position_source__global_position_maybe_empty.destroy_particle()
        self.move_position_source_to_action_middle__position_run()

    def move_position_source_to_action_middle__position_run(self):
        if not self.join_for_move_position_source_to_action_middle__position_run.arrive():
            return
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ).get_interface_position(
                "position<run>"
            )
        )
        self.scheduler.submit(self.execution_action_middle.accept_for_empty_rule_position_run__global_position_marker_a)
        self.scheduler.submit(self.execution_action_middle.accept_for_empty_rule_position_run__global_position_marker_b)
        self.execution_action_middle.accept_when_empty_position_run__global_position_maybe_empty()
