"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.child


class Inner(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<source>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<destination>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class InnerGuarantees:
    def __init__(self):
        self.position_source__move__position_destination = literal.Guarantee()
        self.position_destination__global_position_child = literal.Guarantee()


@final
class InnerExecution:
    def __init__(
        self,
        action: Inner,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = InnerGuarantees()
        self.destruction_connections = destruction_connections
        self.destruction_position_position_destination__global_position_child: literal.Position
        self.join_for_move_position_source_to_position_destination: literal.Join
        self.join_for_empty_rule_position_source: literal.Join

    def accept_for_empty_rule_position_source(self):
        if not self.join_for_empty_rule_position_source.arrive():
            return
        self.move_position_source_to_position_destination()

    def move_position_source_to_position_destination(self):
        if not self.join_for_move_position_source_to_position_destination.arrive():
            return
        self.action.get_interface_position(
            "position<source>"
        ).move_particle_to(
            self.action.get_interface_position(
                "position<destination>"
            )
        )
        self.destruction_position_position_destination__global_position_child = self.action.get_interface_position(
            "position<destination>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.guarantees.position_source__move__position_destination.publish(
            self.scheduler,
            self.destroy_position_destination__global_position_child,
        )

    def destroy_position_destination__global_position_child(self):
        literal.continue_destruction(self.continue_destroy_position_destination__global_position_child)

    def continue_destroy_position_destination__global_position_child(self):
        self.destruction_position_position_destination__global_position_child.destroy_particle()
        self.guarantees.position_destination__global_position_child.publish(
            self.scheduler,
        )
