"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.parent


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_mw = literal.LocalPosition(
            "position<mw>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_mw__action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_position_position_mw__action_middle__position_run: literal.Position
        self.join_for_destroy_position_mw = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_mw()

    def create_position_mw(self):
        self.local_position_mw.create_particle()
        self.execution_position_mw__action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.local_position_mw.particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
        )
        self.execution_position_mw__action_middle.join_for_empty_rule_position_iface = literal.NO_JOIN
        self.execution_position_mw__action_middle.join_for_move_position_iface_to_position_gw__action_inner__position_input = self.scheduler.create_join(2)
        self.execution_position_mw__action_middle.guarantees.position_iface.consumers.append(
            self.destroy_position_mw
        )
        self.scheduler.submit(self.create_position_mw__action_middle__position_iface)
        self.scheduler.submit(self.create_position_mw__action_middle__position_run)
        self.execution_position_mw__action_middle.on_action_parent_occupied()

    def create_position_mw__action_middle__position_iface(self):
        self.local_position_mw.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<iface>"
        ).create_particle()
        self.local_position_mw.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<iface>"
        ).particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).create_particle()
        self.execution_position_mw__action_middle.accept_for_empty_rule_position_iface()

    def create_position_mw__action_middle__position_run(self):
        self.local_position_mw.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_position_position_mw__action_middle__position_run = self.local_position_mw.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<run>"
        )
        self.destruction_position_position_mw__action_middle__position_run.destroy_particle()
        self.destroy_position_mw()

    def destroy_position_mw(self):
        if not self.join_for_destroy_position_mw.arrive():
            return
        self.local_position_mw.destroy_particle()
