"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.middle_known


class Middle(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<target>",
                    constraints=(
                        local.my_domain_com.my_lib.destructor.Destructor,
                        local.my_domain_com.my_lib.middle_known.MiddleKnown,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleGuarantees:
    def __init__(self):
        self.position_target = literal.Guarantee()


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = MiddleGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_position_position_target__global_position_middle_known: literal.Position
        self.join_for_move_position_target_to_action_destroyer__position_target: literal.Join
        self.join_for_empty_rule_position_target: literal.Join
        self.execution_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=self.destruction_connections,
        )
        self.execution_action_destroyer.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_action_destroyer.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_action_destroyer.join_for_destroy_position_target = literal.NO_JOIN
        self.execution_action_destroyer.join_for_destroy_position_run = literal.NO_JOIN

    def accept_when_empty_position_target__global_position_middle_known(self):
        self.create_position_target__global_position_middle_known()

    def accept_for_empty_rule_position_target(self):
        if not self.join_for_empty_rule_position_target.arrive():
            return
        self.move_position_target_to_action_destroyer__position_target()

    def on_action_parent_occupied(self):
        self.create_action_destroyer__position_run()

    def create_position_target__global_position_middle_known(self):
        self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.middle_known.MiddleKnown
        ).create_particle()
        self.destruction_position_position_target__global_position_middle_known = self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.middle_known.MiddleKnown
        )
        self.destruction_position_position_target__global_position_middle_known.destroy_particle()
        self.move_position_target_to_action_destroyer__position_target()

    def move_position_target_to_action_destroyer__position_target(self):
        if not self.join_for_move_position_target_to_action_destroyer__position_target.arrive():
            return
        self.action.get_interface_position(
            "position<target>"
        ).move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.guarantees.position_target.publish(
            self.scheduler,
            self.execution_action_destroyer.accept_when_empty_position_target__global_position_callee_known,
        )

    def create_action_destroyer__position_run(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.execution_action_destroyer.accept_for_empty_rule_position_run()
