"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.worker


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.worker.Worker,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_gateway__action_worker: local.my_domain_com.my_lib.worker.WorkerExecution
        self.destruction_position_position_gateway__action_worker__position_output: literal.Position
        self.destruction_position_position_gateway__action_worker__position_trigger: literal.Position
        self.join_for_destroy_position_gateway = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_gateway()

    def create_position_gateway(self):
        self.local_position_gateway.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway",
            1,
        )
        self.execution_position_gateway__action_worker = local.my_domain_com.my_lib.worker.WorkerExecution(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.worker.Worker
            ),
            self.scheduler,
            self.trace_execution,
            "worker",
        )
        self.execution_position_gateway__action_worker.join_for_empty_rule_position_input = literal.NO_JOIN
        self.execution_position_gateway__action_worker.join_for_move_position_input_to_position_output = literal.NO_JOIN
        self.execution_position_gateway__action_worker.guarantees.position_input__move__position_output.inits.append(
            self.init_position_gateway__action_worker__position_input__move__position_output
        )
        self.execution_position_gateway__action_worker.guarantees.position_input__move__position_output.consumers.append(
            self.destroy_position_gateway__action_worker__position_output
        )
        self.scheduler.submit(self.create_position_gateway__action_worker__position_input)
        self.create_position_gateway__action_worker__position_trigger()

    def create_position_gateway__action_worker__position_input(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<input>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway::/worker::input",
            1,
        )
        self.execution_position_gateway__action_worker.accept_for_empty_rule_position_input()

    def create_position_gateway__action_worker__position_trigger(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway::/worker::trigger",
            1,
        )
        self.destruction_position_position_gateway__action_worker__position_trigger = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger>"
        )
        self.destruction_position_position_gateway__action_worker__position_trigger.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gateway::/worker::trigger",
            1,
        )
        self.destroy_position_gateway()

    def destroy_position_gateway__action_worker__position_output(self):
        self.destruction_position_position_gateway__action_worker__position_output.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gateway::/worker::output",
            1,
        )
        self.destroy_position_gateway()

    def destroy_position_gateway(self):
        if not self.join_for_destroy_position_gateway.arrive():
            return
        self.local_position_gateway.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gateway",
            1,
        )

    def init_position_gateway__action_worker__position_input__move__position_output(self):
        self.destruction_position_position_gateway__action_worker__position_output = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<output>"
        )
