"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.first
import local.my_domain_com.my_lib.second


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.first.First,
        local.my_domain_com.my_lib.second.Second,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.execution_action_first: local.my_domain_com.my_lib.first.FirstExecution
        self.execution_action_second: local.my_domain_com.my_lib.second.SecondExecution
        self.destruction_position_action_first__position_trigger_pos: literal.Position
        self.destruction_position_action_second__position_trigger_pos: literal.Position
        self.execution_action_first = local.my_domain_com.my_lib.first.FirstExecution(
            self.scheduler,
            self.trace_execution,
            "first",
        )
        self.execution_action_second = local.my_domain_com.my_lib.second.SecondExecution(
            self.scheduler,
            self.trace_execution,
            "second",
        )

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_first__position_trigger_pos)
        self.scheduler.submit(self.create_action_second__position_trigger_pos)
        self.scheduler.submit(self.execution_action_first.on_action_parent_occupied)
        self.execution_action_second.on_action_parent_occupied()

    def create_action_first__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.first.First
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/first::trigger_pos",
            1,
        )
        self.destruction_position_action_first__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.first.First
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_first__position_trigger_pos.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/first::trigger_pos",
            1,
        )

    def create_action_second__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.second.Second
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/second::trigger_pos",
            1,
        )
        self.destruction_position_action_second__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.second.Second
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_second__position_trigger_pos.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/second::trigger_pos",
            1,
        )
