"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.input


class Other(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.input.Input,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<holder_a>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<holder_b>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<holder_c>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class OtherGuarantees:
    def __init__(self):
        self.position_holder_a = literal.Guarantee()
        self.position_holder_b = literal.Guarantee()
        self.global_position_input = literal.Guarantee()
        self.position_holder_c = literal.Guarantee()


@final
class OtherExecution:
    def __init__(
        self,
        action: Other,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = OtherGuarantees()
        self.destruction_connections = destruction_connections
        self.destruction_position_global_position_input__global_position_a: literal.Position
        self.join_for_move_global_position_input__global_position_a_to_position_holder_a: literal.Join
        self.join_for_move_position_holder_a_to_position_holder_b: literal.Join
        self.join_for_move_position_holder_b_to_global_position_input__global_position_a = self.scheduler.create_join(2)
        self.join_for_move_global_position_input__global_position_a_to_position_holder_c: literal.Join
        self.join_for_destroy_global_position_input: literal.Join
        self.join_for_empty_rule_global_position_input__global_position_a: literal.Join
        self.join_when_empty_position_holder_b: literal.Join
        self.join_when_empty_position_holder_c: literal.Join
        self.join_for_empty_rule_global_position_input: literal.Join

    def accept_for_empty_rule_global_position_input__global_position_a(self):
        if not self.join_for_empty_rule_global_position_input__global_position_a.arrive():
            return
        self.move_global_position_input__global_position_a_to_position_holder_a()

    def accept_when_empty_position_holder_b(self):
        if not self.join_when_empty_position_holder_b.arrive():
            return
        self.move_position_holder_a_to_position_holder_b()

    def accept_when_empty_position_holder_c(self):
        if not self.join_when_empty_position_holder_c.arrive():
            return
        self.move_global_position_input__global_position_a_to_position_holder_c()

    def accept_for_empty_rule_global_position_input(self):
        if not self.join_for_empty_rule_global_position_input.arrive():
            return
        self.destroy_global_position_input()

    def move_global_position_input__global_position_a_to_position_holder_a(self):
        if not self.join_for_move_global_position_input__global_position_a_to_position_holder_a.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).move_particle_to(
            self.action.get_interface_position(
                "position<holder_a>"
            )
        )
        self.scheduler.submit(self.move_position_holder_a_to_position_holder_b)
        self.create_global_position_input__global_position_a()

    def move_position_holder_a_to_position_holder_b(self):
        if not self.join_for_move_position_holder_a_to_position_holder_b.arrive():
            return
        self.action.get_interface_position(
            "position<holder_a>"
        ).move_particle_to(
            self.action.get_interface_position(
                "position<holder_b>"
            )
        )
        self.guarantees.position_holder_a.publish(
            self.scheduler,
            self.move_position_holder_b_to_global_position_input__global_position_a,
        )

    def create_global_position_input__global_position_a(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.destruction_position_global_position_input__global_position_a = self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        )
        self.destruction_position_global_position_input__global_position_a.destroy_particle()
        self.move_position_holder_b_to_global_position_input__global_position_a()

    def move_position_holder_b_to_global_position_input__global_position_a(self):
        if not self.join_for_move_position_holder_b_to_global_position_input__global_position_a.arrive():
            return
        self.action.get_interface_position(
            "position<holder_b>"
        ).move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.input.Input
            ).particle.get_position(
                local.my_domain_com.my_lib.a.A
            )
        )
        self.guarantees.position_holder_b.publish(
            self.scheduler,
            self.move_global_position_input__global_position_a_to_position_holder_c,
        )

    def move_global_position_input__global_position_a_to_position_holder_c(self):
        if not self.join_for_move_global_position_input__global_position_a_to_position_holder_c.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).move_particle_to(
            self.action.get_interface_position(
                "position<holder_c>"
            )
        )
        self.scheduler.submit(self.destroy_global_position_input)
        self.destroy_position_holder_c()

    def destroy_global_position_input(self):
        if not self.join_for_destroy_global_position_input.arrive():
            return
        literal.continue_destruction(self.continue_destroy_global_position_input)

    def continue_destroy_global_position_input(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).destroy_particle()
        self.guarantees.global_position_input.publish(
            self.scheduler,
        )

    def destroy_position_holder_c(self):
        literal.continue_destruction(self.continue_destroy_position_holder_c)

    def continue_destroy_position_holder_c(self):
        self.action.get_interface_position(
            "position<holder_c>"
        ).destroy_particle()
        self.guarantees.position_holder_c.publish(
            self.scheduler,
        )
