"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.item


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_holder_a = literal.LocalPosition(
            "position<holder_a>",
            scheduler=self.scheduler,
        )
        self.local_position_holder_b = literal.LocalPosition(
            "position<holder_b>",
            scheduler=self.scheduler,
        )
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.item.Item,
            ),
            scheduler=self.scheduler,
        )
        self.destruction_position_position_box__global_position_item: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.item.Item
        ).create_particle()
        self.destruction_position_position_box__global_position_item = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.item.Item
        )
        self.destruction_position_position_box__global_position_item.destroy_particle()
        self.local_position_box.move_particle_to(self.local_position_holder_a)
        self.local_position_holder_a.move_particle_to(self.local_position_holder_b)
        self.local_position_holder_b.destroy_particle()
