"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.brew
import local.my_domain_com.my_lib.grind
import local.my_domain_com.my_lib.heat


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_station = literal.LocalPosition(
            "position<station>",
            constraints=(
                local.my_domain_com.my_lib.grind.Grind,
                local.my_domain_com.my_lib.heat.Heat,
                local.my_domain_com.my_lib.brew.Brew,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_station__action_grind: local.my_domain_com.my_lib.grind.GrindExecution
        self.execution_position_station__action_heat: local.my_domain_com.my_lib.heat.HeatExecution
        self.execution_position_station__action_brew: local.my_domain_com.my_lib.brew.BrewExecution
        self.destruction_position_position_station__action_brew__position_cup: literal.Position
        self.destruction_position_position_station__action_brew__position_spent_puck: literal.Position
        self.join_for_destroy_position_station = self.scheduler.create_join(3)

    def on_action_parent_occupied(self):
        self.create_position_station()

    def create_position_station(self):
        self.local_position_station.create_particle()
        self.execution_position_station__action_grind = local.my_domain_com.my_lib.grind.GrindExecution(
            self.local_position_station.particle.get_action(
                local.my_domain_com.my_lib.grind.Grind
            ),
            self.scheduler,
        )
        self.execution_position_station__action_grind.join_for_empty_rule_position_beans = literal.NO_JOIN
        self.execution_position_station__action_grind.join_for_move_position_beans_to_position_grounds = literal.NO_JOIN
        self.execution_position_station__action_grind.guarantees.position_beans__move__position_grounds.consumers.append(
            self.move_position_station__action_grind__position_grounds_to_position_station__action_brew__position_grounds
        )
        self.execution_position_station__action_heat = local.my_domain_com.my_lib.heat.HeatExecution(
            self.local_position_station.particle.get_action(
                local.my_domain_com.my_lib.heat.Heat
            ),
            self.scheduler,
        )
        self.execution_position_station__action_heat.join_for_empty_rule_position_cold_water = literal.NO_JOIN
        self.execution_position_station__action_heat.join_for_move_position_cold_water_to_position_hot_water = literal.NO_JOIN
        self.execution_position_station__action_heat.guarantees.position_cold_water__move__position_hot_water.consumers.append(
            self.move_position_station__action_heat__position_hot_water_to_position_station__action_brew__position_water
        )
        self.execution_position_station__action_brew = local.my_domain_com.my_lib.brew.BrewExecution(
            self.local_position_station.particle.get_action(
                local.my_domain_com.my_lib.brew.Brew
            ),
            self.scheduler,
        )
        self.execution_position_station__action_brew.join_for_empty_rule_position_water = literal.NO_JOIN
        self.execution_position_station__action_brew.join_for_empty_rule_position_grounds = literal.NO_JOIN
        self.execution_position_station__action_brew.join_for_destroy_position_water = literal.NO_JOIN
        self.execution_position_station__action_brew.join_for_move_position_grounds_to_position_spent_puck = literal.NO_JOIN
        self.execution_position_station__action_brew.guarantees.position_cup.inits.append(
            self.init_position_station__action_brew__position_cup
        )
        self.execution_position_station__action_brew.guarantees.position_cup.consumers.append(
            self.destroy_position_station__action_brew__position_cup
        )
        self.execution_position_station__action_brew.guarantees.position_grounds__move__position_spent_puck.inits.append(
            self.init_position_station__action_brew__position_grounds__move__position_spent_puck
        )
        self.execution_position_station__action_brew.guarantees.position_grounds__move__position_spent_puck.consumers.append(
            self.destroy_position_station__action_brew__position_spent_puck
        )
        self.execution_position_station__action_brew.guarantees.position_water.consumers.append(
            self.destroy_position_station
        )
        self.scheduler.submit(self.create_position_station__action_grind__position_beans)
        self.scheduler.submit(self.create_position_station__action_heat__position_cold_water)
        self.execution_position_station__action_brew.accept_when_empty_position_cup()

    def create_position_station__action_grind__position_beans(self):
        self.local_position_station.particle.get_action(
            local.my_domain_com.my_lib.grind.Grind
        ).get_interface_position(
            "position<beans>"
        ).create_particle()
        self.execution_position_station__action_grind.accept_for_empty_rule_position_beans()

    def create_position_station__action_heat__position_cold_water(self):
        self.local_position_station.particle.get_action(
            local.my_domain_com.my_lib.heat.Heat
        ).get_interface_position(
            "position<cold_water>"
        ).create_particle()
        self.execution_position_station__action_heat.accept_for_empty_rule_position_cold_water()

    def move_position_station__action_grind__position_grounds_to_position_station__action_brew__position_grounds(self):
        self.local_position_station.particle.get_action(
            local.my_domain_com.my_lib.grind.Grind
        ).get_interface_position(
            "position<grounds>"
        ).move_particle_to(
            self.local_position_station.particle.get_action(
                local.my_domain_com.my_lib.brew.Brew
            ).get_interface_position(
                "position<grounds>"
            )
        )
        self.execution_position_station__action_brew.accept_for_empty_rule_position_grounds()

    def move_position_station__action_heat__position_hot_water_to_position_station__action_brew__position_water(self):
        self.local_position_station.particle.get_action(
            local.my_domain_com.my_lib.heat.Heat
        ).get_interface_position(
            "position<hot_water>"
        ).move_particle_to(
            self.local_position_station.particle.get_action(
                local.my_domain_com.my_lib.brew.Brew
            ).get_interface_position(
                "position<water>"
            )
        )
        self.execution_position_station__action_brew.accept_for_empty_rule_position_water()

    def destroy_position_station__action_brew__position_cup(self):
        self.destruction_position_position_station__action_brew__position_cup.destroy_particle()
        self.destroy_position_station()

    def destroy_position_station__action_brew__position_spent_puck(self):
        self.destruction_position_position_station__action_brew__position_spent_puck.destroy_particle()
        self.destroy_position_station()

    def destroy_position_station(self):
        if not self.join_for_destroy_position_station.arrive():
            return
        self.local_position_station.destroy_particle()

    def init_position_station__action_brew__position_cup(self):
        self.destruction_position_position_station__action_brew__position_cup = self.local_position_station.particle.get_action(
            local.my_domain_com.my_lib.brew.Brew
        ).get_interface_position(
            "position<cup>"
        )

    def init_position_station__action_brew__position_grounds__move__position_spent_puck(self):
        self.destruction_position_position_station__action_brew__position_spent_puck = self.local_position_station.particle.get_action(
            local.my_domain_com.my_lib.brew.Brew
        ).get_interface_position(
            "position<spent_puck>"
        )
