"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.grandchild
import local.my_domain_com.my_lib.inner
import local.my_domain_com.my_lib.parent


class Middle(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.Parent,
        local.my_domain_com.my_lib.inner.Inner,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.destruction_connections = destruction_connections
        self.execution_action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_connection_action_inner: literal.DestructionConnection
        self.destruction_position_global_position_parent__global_position_child: literal.Position
        self.destruction_position_global_position_parent__global_position_child__global_position_grandchild: literal.Position
        self.destruction_position_action_inner__position_trigger_pos: literal.Position
        self.join_for_destroy_global_position_parent__global_position_child__global_position_grandchild: literal.Join
        self.join_for_empty_rule_global_position_parent__global_position_child__global_position_grandchild: literal.Join
        self.join_for_empty_rule_global_position_parent: literal.Join
        self.join_for_action_inner__for_empty_rule_global_position_parent: literal.Join
        self.destruction_connection_action_inner = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_global_position_parent__global_position_child,
            forwarded_connection=self.destruction_connections.connection(local.my_domain_com.my_lib.inner.InnerExecution.continue_destroy_global_position_parent) if self.destruction_connections is not None else None,
        )
        self.execution_action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.inner.InnerExecution.continue_destroy_global_position_parent: self.destruction_connection_action_inner,
            },
            forwarded=self.destruction_connections,
            ),
        )
        self.execution_action_inner.join_for_empty_rule_global_position_parent = literal.NO_JOIN
        self.execution_action_inner.join_for_destroy_global_position_parent = literal.NO_JOIN

    def accept_for_empty_rule_global_position_parent__global_position_child__global_position_grandchild(self):
        if not self.join_for_empty_rule_global_position_parent__global_position_child__global_position_grandchild.arrive():
            return
        self.destruction_position_global_position_parent__global_position_child__global_position_grandchild = self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.Grandchild
        )
        self.destroy_global_position_parent__global_position_child__global_position_grandchild()

    def on_action_parent_occupied(self):
        self.create_action_inner__position_trigger_pos()

    def accept_for_empty_rule_global_position_parent(self):
        if not self.join_for_empty_rule_global_position_parent.arrive():
            return
        self.action_inner__for_empty_rule_global_position_parent()

    def destroy_global_position_parent__global_position_child__global_position_grandchild(self):
        if not self.join_for_destroy_global_position_parent__global_position_child__global_position_grandchild.arrive():
            return
        literal.continue_destruction(self.continue_destroy_global_position_parent__global_position_child__global_position_grandchild)

    def continue_destroy_global_position_parent__global_position_child__global_position_grandchild(self):
        self.destruction_position_global_position_parent__global_position_child__global_position_grandchild.destroy_particle()
        self.action_inner__for_empty_rule_global_position_parent()

    def create_action_inner__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_inner__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_inner__position_trigger_pos.destroy_particle()

    def destroy_global_position_parent__global_position_child(self):
        literal.continue_destruction(self.continue_destroy_global_position_parent__global_position_child)

    def continue_destroy_global_position_parent__global_position_child(self):
        self.destruction_position_global_position_parent__global_position_child.destroy_particle()
        self.destruction_connection_action_inner.complete()

    def action_inner__for_empty_rule_global_position_parent(self):
        if not self.join_for_action_inner__for_empty_rule_global_position_parent.arrive():
            return
        self.destruction_position_global_position_parent__global_position_child = self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.execution_action_inner.accept_for_empty_rule_global_position_parent()
