"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.inner


class MiddleAction(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.inner.Inner,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleActionExecution:
    def __init__(
        self,
        action: MiddleAction,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.destruction_connections = destruction_connections
        self.execution_action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_position_action_inner__position_trigger_pos: literal.Position
        self.join_for_empty_rule_global_position_intermediate: literal.Join
        self.join_for_empty_rule_global_position_input__global_position_b: literal.Join
        self.join_for_empty_rule_global_position_input: literal.Join
        self.execution_action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ),
            self.scheduler,
            destruction_connections=self.destruction_connections,
        )

    def on_action_parent_occupied(self):
        self.create_action_inner__position_trigger_pos()

    def accept_for_empty_rule_global_position_intermediate(self):
        if not self.join_for_empty_rule_global_position_intermediate.arrive():
            return
        self.execution_action_inner.accept_for_empty_rule_global_position_intermediate()

    def accept_for_empty_rule_global_position_input__global_position_b(self):
        if not self.join_for_empty_rule_global_position_input__global_position_b.arrive():
            return
        self.execution_action_inner.accept_for_empty_rule_global_position_input__global_position_b()

    def accept_for_empty_rule_global_position_input(self):
        if not self.join_for_empty_rule_global_position_input.arrive():
            return
        self.execution_action_inner.accept_for_empty_rule_global_position_input()

    def create_action_inner__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_inner__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_inner__position_trigger_pos.destroy_particle()
