"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.fill_item
import local.my_domain_com.my_lib.outer


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.fill_item.FillItem,
        local.my_domain_com.my_lib.outer.Outer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
        )
        scheduler.submit(execution.on_action_parent_occupied)
        execution.accept_when_empty_global_position_item()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.execution_action_fill_item: local.my_domain_com.my_lib.fill_item.FillItemExecution
        self.execution_action_outer: local.my_domain_com.my_lib.outer.OuterExecution
        self.destruction_position_action_fill_item__position_trigger_pos: literal.Position
        self.destruction_position_action_outer__position_trigger_pos: literal.Position
        self.execution_action_fill_item = local.my_domain_com.my_lib.fill_item.FillItemExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.fill_item.FillItem
            ),
            self.scheduler,
            self.trace_execution,
            "fill_item",
        )
        self.execution_action_fill_item.guarantees.global_position_item.consumers.append(
            self.accept_guarantee_action_outer
        )
        self.execution_action_outer = local.my_domain_com.my_lib.outer.OuterExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ),
            self.scheduler,
            self.trace_execution,
            "outer",
        )
        self.execution_action_outer.execution_action_middle.execution_action_empty_item.join_for_empty_rule_global_position_item = literal.NO_JOIN
        self.execution_action_outer.execution_action_middle.execution_action_empty_item.join_for_destroy_global_position_item = literal.NO_JOIN
        self.execution_action_outer.execution_action_middle.join_for_empty_rule_global_position_item = literal.NO_JOIN
        self.execution_action_outer.join_for_empty_rule_global_position_item = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_fill_item__position_trigger_pos)
        self.scheduler.submit(self.create_action_outer__position_trigger_pos)
        self.execution_action_outer.on_action_parent_occupied()

    def accept_when_empty_global_position_item(self):
        self.execution_action_fill_item.accept_when_empty_global_position_item()

    def create_action_fill_item__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.fill_item.FillItem
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/fill_item::trigger_pos",
            1,
        )
        self.destruction_position_action_fill_item__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.fill_item.FillItem
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_fill_item__position_trigger_pos.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/fill_item::trigger_pos",
            1,
        )

    def create_action_outer__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/outer::trigger_pos",
            1,
        )
        self.destruction_position_action_outer__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_outer__position_trigger_pos.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/outer::trigger_pos",
            1,
        )

    def accept_guarantee_action_outer(self):
        self.execution_action_outer.accept_for_empty_rule_global_position_item()
