"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.consumer
import local.my_domain_com.my_lib.input
import local.my_domain_com.my_lib.producer


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.input.Input,
        local.my_domain_com.my_lib.producer.Producer,
        local.my_domain_com.my_lib.consumer.Consumer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.execution_action_producer.join_for_empty_rule_global_position_input = scheduler.create_join(2)
        execution.join_when_empty_global_position_box = literal.NO_JOIN
        scheduler.submit(execution.accept_when_empty_global_position_input)
        scheduler.submit(execution.on_action_parent_occupied)
        execution.accept_when_empty_global_position_box()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_producer: local.my_domain_com.my_lib.producer.ProducerExecution
        self.execution_action_consumer: local.my_domain_com.my_lib.consumer.ConsumerExecution
        self.destruction_position_action_producer__position_trigger_pos: literal.Position
        self.destruction_position_action_consumer__position_trigger_pos: literal.Position
        self.join_when_empty_global_position_box: literal.Join
        self.execution_action_producer = local.my_domain_com.my_lib.producer.ProducerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.producer.Producer
            ),
            self.scheduler,
        )
        self.execution_action_producer.join_for_move_global_position_input_to_global_position_box = literal.NO_JOIN
        self.execution_action_producer.guarantees.global_position_input__move__global_position_box.consumers.append(
            self.accept_guarantee_action_consumer
        )
        self.execution_action_consumer = local.my_domain_com.my_lib.consumer.ConsumerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.consumer.Consumer
            ),
            self.scheduler,
        )
        self.execution_action_consumer.join_when_empty_global_position_box__global_position_destination = literal.NO_JOIN
        self.execution_action_consumer.join_for_move_global_position_box__global_position_item_to_global_position_box__global_position_destination = literal.NO_JOIN

    def accept_when_empty_global_position_input(self):
        self.create_global_position_input()

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_producer__position_trigger_pos)
        self.create_action_consumer__position_trigger_pos()

    def accept_when_empty_global_position_box(self):
        if not self.join_when_empty_global_position_box.arrive():
            return
        self.execution_action_producer.accept_for_empty_rule_global_position_input()

    def create_global_position_input(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.input.Input
        ).create_particle()
        self.execution_action_producer.accept_for_empty_rule_global_position_input()

    def create_action_producer__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.producer.Producer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_producer__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.producer.Producer
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_producer__position_trigger_pos.destroy_particle()

    def create_action_consumer__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.consumer.Consumer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_consumer__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.consumer.Consumer
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_consumer__position_trigger_pos.destroy_particle()

    def accept_guarantee_action_consumer(self):
        self.execution_action_consumer.accept_when_empty_global_position_box__global_position_item()
