"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_library_collection.inner_position


class PerformOperation(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<operation_trigger>",
                    constraints=(
                        local.my_domain_com.my_library_collection.inner_position.InnerPosition,
                    ),
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class PerformOperationGuarantees:
    def __init__(self):
        self.position_operation_trigger = literal.Guarantee()
        self.position_run = literal.Guarantee()


@final
class PerformOperationExecution:
    def __init__(
        self,
        action: PerformOperation,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = PerformOperationGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_result = literal.LocalPosition(
            "position<result>",
            scheduler=self.scheduler,
        )
        self.destruction_position_position_operation_trigger__global_position_inner_position: literal.Position
        self.join_for_destroy_position_operation_trigger__global_position_inner_position: literal.Join
        self.join_for_destroy_position_operation_trigger: literal.Join
        self.join_for_destroy_position_run: literal.Join
        self.join_for_empty_rule_position_operation_trigger__global_position_inner_position: literal.Join
        self.join_for_empty_rule_position_operation_trigger: literal.Join
        self.join_for_empty_rule_position_run: literal.Join

    def on_action_parent_occupied(self):
        self.create_position_result()

    def accept_for_empty_rule_position_operation_trigger__global_position_inner_position(self):
        if not self.join_for_empty_rule_position_operation_trigger__global_position_inner_position.arrive():
            return
        self.destruction_position_position_operation_trigger__global_position_inner_position = self.action.get_interface_position(
            "position<operation_trigger>"
        ).particle.get_position(
            local.my_domain_com.my_library_collection.inner_position.InnerPosition
        )
        self.destroy_position_operation_trigger__global_position_inner_position()

    def accept_for_empty_rule_position_operation_trigger(self):
        if not self.join_for_empty_rule_position_operation_trigger.arrive():
            return
        self.destroy_position_operation_trigger()

    def accept_for_empty_rule_position_run(self):
        if not self.join_for_empty_rule_position_run.arrive():
            return
        self.destroy_position_run()

    def create_position_result(self):
        self.local_position_result.create_particle()
        self.local_position_result.destroy_particle()

    def destroy_position_operation_trigger__global_position_inner_position(self):
        if not self.join_for_destroy_position_operation_trigger__global_position_inner_position.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_operation_trigger__global_position_inner_position)

    def continue_destroy_position_operation_trigger__global_position_inner_position(self):
        self.destruction_position_position_operation_trigger__global_position_inner_position.destroy_particle()
        self.destroy_position_operation_trigger()

    def destroy_position_operation_trigger(self):
        if not self.join_for_destroy_position_operation_trigger.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_operation_trigger)

    def continue_destroy_position_operation_trigger(self):
        self.action.get_interface_position(
            "position<operation_trigger>"
        ).destroy_particle()
        self.guarantees.position_operation_trigger.publish(
            self.scheduler,
        )

    def destroy_position_run(self):
        if not self.join_for_destroy_position_run.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_run)

    def continue_destroy_position_run(self):
        self.action.get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.guarantees.position_run.publish(
            self.scheduler,
        )
