"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.grandchild
import local.my_domain_com.my_lib.greatgrandchild
import local.my_domain_com.my_lib.inner
import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.parent
import local.my_domain_com.my_lib.sibling


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.parent.Parent,
        local.my_domain_com.my_lib.middle.Middle,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        scheduler.submit(execution.accept_when_empty_global_position_parent)
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_connection_action_middle: literal.DestructionConnection
        self.destruction_connection_action_middle_2: literal.DestructionConnection
        self.destruction_position_global_position_parent__global_position_child__global_position_grandchild__global_position_greatgrandchild: literal.Position
        self.destruction_position_global_position_parent__global_position_sibling: literal.Position
        self.destruction_position_action_middle__position_trigger_pos: literal.Position
        self.destruction_connection_action_middle = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_global_position_parent__global_position_child__global_position_grandchild__global_position_greatgrandchild,
        )
        self.destruction_connection_action_middle_2 = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_global_position_parent__global_position_sibling,
        )
        self.execution_action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.middle.MiddleExecution.continue_destroy_global_position_parent__global_position_child__global_position_grandchild: self.destruction_connection_action_middle,
                local.my_domain_com.my_lib.inner.InnerExecution.continue_destroy_global_position_parent: self.destruction_connection_action_middle_2,
            },
            ),
        )
        self.execution_action_middle.join_for_empty_rule_global_position_parent__global_position_child__global_position_grandchild = literal.NO_JOIN
        self.execution_action_middle.join_for_empty_rule_global_position_parent = literal.NO_JOIN
        self.execution_action_middle.join_for_destroy_global_position_parent__global_position_child__global_position_grandchild = literal.NO_JOIN
        self.execution_action_middle.join_for_action_inner__for_empty_rule_global_position_parent = self.scheduler.create_join(2)

    def accept_when_empty_global_position_parent(self):
        self.create_global_position_parent()

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_middle__position_trigger_pos)
        self.execution_action_middle.on_action_parent_occupied()

    def create_global_position_parent(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).create_particle()
        self.scheduler.submit(self.create_global_position_parent__global_position_child)
        self.create_global_position_parent__global_position_sibling()

    def create_global_position_parent__global_position_child(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.Grandchild
        ).create_particle()
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.Grandchild
        ).particle.get_position(
            local.my_domain_com.my_lib.greatgrandchild.Greatgrandchild
        ).create_particle()
        self.destruction_position_global_position_parent__global_position_child__global_position_grandchild__global_position_greatgrandchild = self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.grandchild.Grandchild
        ).particle.get_position(
            local.my_domain_com.my_lib.greatgrandchild.Greatgrandchild
        )
        self.execution_action_middle.accept_for_empty_rule_global_position_parent__global_position_child__global_position_grandchild()

    def create_global_position_parent__global_position_sibling(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.sibling.Sibling
        ).create_particle()
        self.destruction_position_global_position_parent__global_position_sibling = self.action.on_particle.get_position(
            local.my_domain_com.my_lib.parent.Parent
        ).particle.get_position(
            local.my_domain_com.my_lib.sibling.Sibling
        )
        self.execution_action_middle.accept_for_empty_rule_global_position_parent()

    def create_action_middle__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_middle__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_middle__position_trigger_pos.destroy_particle()

    def destroy_global_position_parent__global_position_child__global_position_grandchild__global_position_greatgrandchild(self):
        self.destruction_position_global_position_parent__global_position_child__global_position_grandchild__global_position_greatgrandchild.destroy_particle()
        self.destruction_connection_action_middle.complete()

    def destroy_global_position_parent__global_position_sibling(self):
        self.destruction_position_global_position_parent__global_position_sibling.destroy_particle()
        self.destruction_connection_action_middle_2.complete()
