"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.child_destructor
import local.my_domain_com.my_lib.parent_destructor


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.parent_destructor.ParentDestructor,
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_parent_destructor: local.my_domain_com.my_lib.parent_destructor.ParentDestructorExecution
        self.execution_position_box__global_position_child__action_child_destructor: local.my_domain_com.my_lib.child_destructor.ChildDestructorExecution
        self.destruction_position_position_box__global_position_child: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_parent_destructor = local.my_domain_com.my_lib.parent_destructor.ParentDestructorExecution(
            self.scheduler,
        )
        self.scheduler.submit(self.create_position_box__global_position_child)
        self.execution_position_box__action_parent_destructor.on_action_parent_occupied()

    def create_position_box__global_position_child(self):
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.destruction_position_position_box__global_position_child = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.execution_position_box__global_position_child__action_child_destructor = local.my_domain_com.my_lib.child_destructor.ChildDestructorExecution(
            self.scheduler,
        )
        self.scheduler.submit(self.destroy_position_box)
        self.scheduler.submit(self.destroy_position_box__global_position_child)
        self.execution_position_box__global_position_child__action_child_destructor.on_action_parent_occupied()

    def destroy_position_box(self):
        self.local_position_box.destroy_particle()

    def destroy_position_box__global_position_child(self):
        self.destruction_position_position_box__global_position_child.destroy_particle()
