"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.marker


class Filler(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.marker.Marker,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class FillerGuarantees:
    def __init__(self):
        self.global_position_marker = literal.Guarantee()
        self.position_trigger_pos = literal.Guarantee()


@final
class FillerExecution:
    def __init__(
        self,
        action: Filler,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = FillerGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_holder = literal.LocalPosition(
            "position<holder>",
            scheduler=self.scheduler,
        )
        self.join_for_move_global_position_marker_to_position_holder: literal.Join
        self.join_for_destroy_position_trigger_pos: literal.Join
        self.join_for_empty_rule_global_position_marker: literal.Join
        self.join_for_empty_rule_position_trigger_pos: literal.Join

    def accept_for_empty_rule_global_position_marker(self):
        if not self.join_for_empty_rule_global_position_marker.arrive():
            return
        self.move_global_position_marker_to_position_holder()

    def accept_for_empty_rule_position_trigger_pos(self):
        if not self.join_for_empty_rule_position_trigger_pos.arrive():
            return
        self.destroy_position_trigger_pos()

    def move_global_position_marker_to_position_holder(self):
        if not self.join_for_move_global_position_marker_to_position_holder.arrive():
            return
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).move_particle_to(self.local_position_holder)
        self.local_position_holder.move_particle_to(
            self.action.on_particle.get_position(
                local.my_domain_com.my_lib.marker.Marker
            )
        )
        self.guarantees.global_position_marker.publish(
            self.scheduler,
        )

    def destroy_position_trigger_pos(self):
        if not self.join_for_destroy_position_trigger_pos.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_trigger_pos)

    def continue_destroy_position_trigger_pos(self):
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.guarantees.position_trigger_pos.publish(
            self.scheduler,
        )
