"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.caller_destructor
import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.earlier_assigned_destructor
import local.my_domain_com.my_lib.later_assigned_destructor
import local.my_domain_com.my_lib.marker


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_destroyer_particle = literal.LocalPosition(
            "position<destroyer_particle>",
            constraints=(
                local.my_domain_com.my_lib.destroyer.Destroyer,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.earlier_assigned_destructor.EarlierAssignedDestructor,
                local.my_domain_com.my_lib.caller_destructor.CallerDestructor,
                local.my_domain_com.my_lib.later_assigned_destructor.LaterAssignedDestructor,
                local.my_domain_com.my_lib.marker.Marker,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_destroyer_particle__action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_position_destroyer_particle__action_destroyer: literal.DestructionConnection
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_caller_destructor: local.my_domain_com.my_lib.caller_destructor.CallerDestructorExecution
        self.destruction_position_position_destroyer_particle__action_destroyer__position_trigger_pos: literal.Position
        self.join_for_move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target = self.scheduler.create_join(2)
        self.join_for_destroy_position_destroyer_particle = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_destroyer_particle)
        self.create_position_carrier()

    def create_position_destroyer_particle(self):
        self.local_position_destroyer_particle.create_particle()
        self.destruction_connection_position_destroyer_particle__action_destroyer = literal.DestructionConnection(
            self.scheduler,
            1,
            self.position_destroyer_particle__action_destroyer__position_target__action_caller_destructor__when_empty_global_position_marker,
        )
        self.execution_position_destroyer_particle__action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.local_position_destroyer_particle.particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_target: self.destruction_connection_position_destroyer_particle__action_destroyer,
            },
            ),
        )
        self.execution_position_destroyer_particle__action_destroyer.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer.join_for_destroy_position_target = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer.guarantees.position_target.consumers.append(
            self.destroy_position_destroyer_particle
        )
        self.scheduler.submit(self.move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target)
        self.create_position_destroyer_particle__action_destroyer__position_trigger_pos()

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target()

    def move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target(self):
        if not self.join_for_move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.local_position_destroyer_particle.particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_caller_destructor = local.my_domain_com.my_lib.caller_destructor.CallerDestructorExecution(
            self.local_position_destroyer_particle.particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.caller_destructor.CallerDestructor
            ),
            self.scheduler,
        )
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_caller_destructor.guarantees.global_position_marker.consumers.append(
            self.destruction_connection_position_destroyer_particle__action_destroyer.complete
        )
        self.execution_position_destroyer_particle__action_destroyer.init_when_occupied_position_target()
        self.execution_position_destroyer_particle__action_destroyer.accept_when_empty_position_target__global_position_marker()

    def create_position_destroyer_particle__action_destroyer__position_trigger_pos(self):
        self.local_position_destroyer_particle.particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_destroyer_particle__action_destroyer__position_trigger_pos = self.local_position_destroyer_particle.particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.scheduler.submit(self.destroy_position_destroyer_particle)
        self.destroy_position_destroyer_particle__action_destroyer__position_trigger_pos()

    def destroy_position_destroyer_particle(self):
        if not self.join_for_destroy_position_destroyer_particle.arrive():
            return
        self.local_position_destroyer_particle.destroy_particle()

    def destroy_position_destroyer_particle__action_destroyer__position_trigger_pos(self):
        self.destruction_position_position_destroyer_particle__action_destroyer__position_trigger_pos.destroy_particle()

    def position_destroyer_particle__action_destroyer__position_target__action_caller_destructor__when_empty_global_position_marker(self):
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_caller_destructor.accept_when_empty_global_position_marker()
