"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.first_destructor
import local.my_domain_com.my_lib.second
import local.my_domain_com.my_lib.second_destructor
import local.my_domain_com.my_lib.third_destructor


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.first_destructor.FirstDestructor,
                local.my_domain_com.my_lib.second.Second,
                local.my_domain_com.my_lib.second_destructor.SecondDestructor,
                local.my_domain_com.my_lib.third_destructor.ThirdDestructor,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_action_destroyer: literal.DestructionConnection
        self.destruction_position_action_destroyer__position_target__global_position_second: literal.Position
        self.destruction_connection_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_action_destroyer__position_target__global_position_second,
        )
        self.execution_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_target: self.destruction_connection_action_destroyer,
            },
            ),
        )
        self.execution_action_destroyer.join_for_empty_rule_position_target__global_position_second = literal.NO_JOIN
        self.execution_action_destroyer.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_action_destroyer.join_for_destroy_position_target = self.scheduler.create_join(4)

    def on_action_parent_occupied(self):
        self.create_position_carrier()

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.second.Second
        ).create_particle()
        self.local_position_carrier.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.destruction_position_action_destroyer__position_target__global_position_second = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.second.Second
        )
        self.execution_action_destroyer.init_when_occupied_position_target()
        self.execution_action_destroyer.execution_position_target__action_second_destructor.join_for_empty_rule_global_position_second = literal.NO_JOIN
        self.execution_action_destroyer.execution_position_target__action_second_destructor.join_for_move_global_position_second_to_position_holder = literal.NO_JOIN
        self.scheduler.submit(self.execution_action_destroyer.accept_when_empty_position_target__global_position_first)
        self.scheduler.submit(self.execution_action_destroyer.accept_when_empty_position_target__global_position_third)
        self.scheduler.submit(self.execution_action_destroyer.accept_for_empty_rule_position_target__global_position_second)
        self.execution_action_destroyer.accept_when_empty_position_target__global_position_marker()

    def destroy_action_destroyer__position_target__global_position_second(self):
        self.destruction_position_action_destroyer__position_target__global_position_second.destroy_particle()
        self.destruction_connection_action_destroyer.complete()
