"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.known_empty
import local.my_domain_com.my_lib.known_occupied
import local.my_domain_com.my_lib.maybe_child


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.execution_action_destroyer.join_when_empty_global_position_destination = literal.NO_JOIN
        execution.execution_action_destroyer.join_for_move_position_local__global_position_known_empty_to_global_position_destination = scheduler.create_join(2)
        execution.join_when_empty_global_position_target = literal.NO_JOIN
        execution.join_when_empty_global_position_destination = literal.NO_JOIN
        execution.join_for_action_destroyer__for_empty_rule_position_run = scheduler.create_join(2)
        scheduler.submit(execution.on_action_parent_occupied)
        scheduler.submit(execution.accept_when_empty_global_position_target)
        execution.accept_when_empty_global_position_destination()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.known_empty.KnownEmpty,
                local.my_domain_com.my_lib.known_occupied.KnownOccupied,
                local.my_domain_com.my_lib.maybe_child.MaybeChild,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_action_destroyer: literal.DestructionConnection
        self.destruction_position_action_destroyer__position_run__global_position_maybe_child: literal.Position
        self.destruction_position_position_source__global_position_known_occupied: literal.Position
        self.join_for_move_position_source_to_action_destroyer__position_run = self.scheduler.create_join(3)
        self.join_when_empty_global_position_target: literal.Join
        self.join_when_empty_global_position_destination: literal.Join
        self.join_for_action_destroyer__for_empty_rule_position_run: literal.Join
        self.destruction_connection_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_action_destroyer__position_run__global_position_maybe_child,
        )
        self.execution_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_local: self.destruction_connection_action_destroyer,
            },
            ),
        )
        self.execution_action_destroyer.join_for_empty_rule_position_run = literal.NO_JOIN
        self.execution_action_destroyer.join_for_move_position_run_to_global_position_target = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.create_position_source()

    def accept_when_empty_global_position_target(self):
        if not self.join_when_empty_global_position_target.arrive():
            return
        self.action_destroyer__for_empty_rule_position_run()

    def accept_when_empty_global_position_destination(self):
        if not self.join_when_empty_global_position_destination.arrive():
            return
        self.execution_action_destroyer.accept_when_empty_global_position_destination()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.scheduler.submit(self.create_position_source__global_position_known_empty)
        self.scheduler.submit(self.create_position_source__global_position_known_occupied)
        self.create_position_source__global_position_maybe_child()

    def create_position_source__global_position_known_empty(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.known_empty.KnownEmpty
        ).create_particle()
        self.move_position_source_to_action_destroyer__position_run()

    def create_position_source__global_position_known_occupied(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.known_occupied.KnownOccupied
        ).create_particle()
        self.destruction_position_position_source__global_position_known_occupied = self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.known_occupied.KnownOccupied
        )
        self.destruction_position_position_source__global_position_known_occupied.destroy_particle()
        self.move_position_source_to_action_destroyer__position_run()

    def create_position_source__global_position_maybe_child(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.maybe_child.MaybeChild
        ).create_particle()
        self.move_position_source_to_action_destroyer__position_run()

    def move_position_source_to_action_destroyer__position_run(self):
        if not self.join_for_move_position_source_to_action_destroyer__position_run.arrive():
            return
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<run>"
            )
        )
        self.action_destroyer__for_empty_rule_position_run()

    def destroy_action_destroyer__position_run__global_position_maybe_child(self):
        self.destruction_position_action_destroyer__position_run__global_position_maybe_child.destroy_particle()
        self.destruction_connection_action_destroyer.complete()

    def action_destroyer__for_empty_rule_position_run(self):
        if not self.join_for_action_destroyer__for_empty_rule_position_run.arrive():
            return
        self.destruction_position_action_destroyer__position_run__global_position_maybe_child = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.maybe_child.MaybeChild
        )
        self.execution_action_destroyer.accept_for_empty_rule_position_run()
