"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.c
import local.my_domain_com.my_lib.d


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_a = literal.LocalPosition(
            "position<a>",
            constraints=(
                local.my_domain_com.my_lib.b.B,
            ),
            scheduler=self.scheduler,
        )
        self.destruction_position_position_a__global_position_b: literal.Position
        self.destruction_position_position_a__global_position_b__global_position_c: literal.Position
        self.destruction_position_position_a__global_position_b__global_position_c__global_position_d: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_a()

    def create_position_a(self):
        self.local_position_a.create_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).create_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        ).create_particle()
        self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        ).particle.get_position(
            local.my_domain_com.my_lib.d.D
        ).create_particle()
        self.destruction_position_position_a__global_position_b = self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        )
        self.destruction_position_position_a__global_position_b__global_position_c = self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        )
        self.destruction_position_position_a__global_position_b__global_position_c__global_position_d = self.local_position_a.particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).particle.get_position(
            local.my_domain_com.my_lib.c.C
        ).particle.get_position(
            local.my_domain_com.my_lib.d.D
        )
        self.scheduler.submit(self.destroy_position_a)
        self.scheduler.submit(self.destroy_position_a__global_position_b)
        self.scheduler.submit(self.destroy_position_a__global_position_b__global_position_c)
        self.destroy_position_a__global_position_b__global_position_c__global_position_d()

    def destroy_position_a(self):
        self.local_position_a.destroy_particle()

    def destroy_position_a__global_position_b(self):
        self.destruction_position_position_a__global_position_b.destroy_particle()

    def destroy_position_a__global_position_b__global_position_c(self):
        self.destruction_position_position_a__global_position_b__global_position_c.destroy_particle()

    def destroy_position_a__global_position_b__global_position_c__global_position_d(self):
        self.destruction_position_position_a__global_position_b__global_position_c__global_position_d.destroy_particle()
