"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal
from define.runtime import tracing

import local.my_domain_com.my_lib.callee
import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.later


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.callee.Callee,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.destructor.Destructor,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_later_box = literal.LocalPosition(
            "position<later_box>",
            constraints=(
                local.my_domain_com.my_lib.later.Later,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_callee: local.my_domain_com.my_lib.callee.CalleeExecution
        self.destruction_connection_position_box__action_callee: tracing.DestructionConnection
        self.execution_position_later_box__action_later: local.my_domain_com.my_lib.later.LaterExecution
        self.destruction_connection_position_later_box__action_later: tracing.DestructionConnection
        self.destruction_position_position_box__action_callee__position_run: literal.Position
        self.destruction_position_position_later_box__action_later__position_run: literal.Position
        self.join_for_move_position_carrier_to_position_box__action_callee__position_target = self.scheduler.create_join(2)
        self.join_for_move_position_carrier_to_position_later_box__action_later__position_target = self.scheduler.create_join(2)
        self.join_for_destroy_position_box = self.scheduler.create_join(2)
        self.join_for_destroy_position_later_box = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_box)
        self.scheduler.submit(self.create_position_later_box)
        self.create_position_carrier()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box",
            1,
        )
        self.destruction_connection_position_box__action_callee = tracing.DestructionConnection(
            self.scheduler,
            0,
            self.run_position_box__action_callee__position_target__action_destructor,
        )
        self.execution_position_box__action_callee = local.my_domain_com.my_lib.callee.CalleeExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.callee.Callee
            ),
            self.scheduler,
            self.trace_execution,
            "callee",
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.callee.CalleeExecution.continue_destroy_position_target: self.destruction_connection_position_box__action_callee,
            },
            ),
        )
        self.execution_position_box__action_callee.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_position_box__action_callee.join_for_destroy_position_target = literal.NO_JOIN
        self.execution_position_box__action_callee.guarantees.position_target.consumers.append(
            self.destroy_position_box
        )
        self.scheduler.submit(self.move_position_carrier_to_position_box__action_callee__position_target)
        self.create_position_box__action_callee__position_run()

    def create_position_later_box(self):
        self.local_position_later_box.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "later_box",
            1,
        )
        self.destruction_connection_position_later_box__action_later = tracing.DestructionConnection(
            self.scheduler,
            0,
            self.run_position_later_box__action_later__position_target__action_destructor,
        )
        self.execution_position_later_box__action_later = local.my_domain_com.my_lib.later.LaterExecution(
            self.local_position_later_box.particle.get_action(
                local.my_domain_com.my_lib.later.Later
            ),
            self.scheduler,
            self.trace_execution,
            "later",
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.later.LaterExecution.continue_destroy_position_target: self.destruction_connection_position_later_box__action_later,
            },
            ),
        )
        self.execution_position_later_box__action_later.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_position_later_box__action_later.join_for_destroy_position_target = literal.NO_JOIN
        self.execution_position_later_box__action_later.guarantees.position_target.consumers.append(
            self.destroy_position_later_box
        )
        self.scheduler.submit(self.move_position_carrier_to_position_later_box__action_later__position_target)
        self.create_position_later_box__action_later__position_run()

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier",
            1,
        )
        self.move_position_carrier_to_position_box__action_callee__position_target()

    def move_position_carrier_to_position_box__action_callee__position_target(self):
        if not self.join_for_move_position_carrier_to_position_box__action_callee__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.callee.Callee
            ).get_interface_position(
                "position<target>"
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "carrier",
            "box::/callee::target",
            1,
        )
        self.scheduler.submit(self.create_position_carrier_2)
        self.execution_position_box__action_callee.accept_for_empty_rule_position_target()

    def create_position_carrier_2(self):
        self.local_position_carrier.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier",
            2,
        )
        self.move_position_carrier_to_position_later_box__action_later__position_target()

    def move_position_carrier_to_position_later_box__action_later__position_target(self):
        if not self.join_for_move_position_carrier_to_position_later_box__action_later__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.local_position_later_box.particle.get_action(
                local.my_domain_com.my_lib.later.Later
            ).get_interface_position(
                "position<target>"
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "carrier",
            "later_box::/later::target",
            1,
        )
        self.execution_position_later_box__action_later.accept_for_empty_rule_position_target()

    def create_position_box__action_callee__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box::/callee::run",
            1,
        )
        self.destruction_position_position_box__action_callee__position_run = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<run>"
        )
        self.scheduler.submit(self.destroy_position_box)
        self.destroy_position_box__action_callee__position_run()

    def create_position_later_box__action_later__position_run(self):
        self.local_position_later_box.particle.get_action(
            local.my_domain_com.my_lib.later.Later
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "later_box::/later::run",
            1,
        )
        self.destruction_position_position_later_box__action_later__position_run = self.local_position_later_box.particle.get_action(
            local.my_domain_com.my_lib.later.Later
        ).get_interface_position(
            "position<run>"
        )
        self.scheduler.submit(self.destroy_position_later_box)
        self.destroy_position_later_box__action_later__position_run()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box",
            1,
        )

    def destroy_position_box__action_callee__position_run(self):
        self.destruction_position_position_box__action_callee__position_run.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/callee::run",
            1,
        )

    def destroy_position_later_box(self):
        if not self.join_for_destroy_position_later_box.arrive():
            return
        self.local_position_later_box.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "later_box",
            1,
        )

    def destroy_position_later_box__action_later__position_run(self):
        self.destruction_position_position_later_box__action_later__position_run.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "later_box::/later::run",
            1,
        )

    def run_position_box__action_callee__position_target__action_destructor(self):
        execution = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
            self.destruction_connection_position_box__action_callee.trace_execution,
            "destructor",
        )
        execution.on_action_parent_occupied()

    def run_position_later_box__action_later__position_target__action_destructor(self):
        execution = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
            self.destruction_connection_position_later_box__action_later.trace_execution,
            "destructor#2",
        )
        execution.on_action_parent_occupied()
