"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.destructor


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<target>",
                    constraints=(
                        local.my_domain_com.my_lib.destructor.Destructor,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.position_target = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_position_target__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.join_for_destroy_position_target: literal.Join
        self.join_for_empty_rule_position_target__global_position_occupied_last: literal.Join
        self.join_for_empty_rule_position_target__global_position_occupied_first: literal.Join
        self.join_for_empty_rule_position_target: literal.Join

    def accept_when_empty_position_target__global_position_empty(self):
        self.execution_position_target__action_destructor.accept_when_empty_global_position_empty()

    def accept_for_empty_rule_position_target__global_position_occupied_last(self):
        if not self.join_for_empty_rule_position_target__global_position_occupied_last.arrive():
            return
        self.execution_position_target__action_destructor.accept_for_empty_rule_global_position_occupied_last()

    def accept_for_empty_rule_position_target__global_position_occupied_first(self):
        if not self.join_for_empty_rule_position_target__global_position_occupied_first.arrive():
            return
        self.execution_position_target__action_destructor.accept_for_empty_rule_global_position_occupied_first()

    def accept_for_empty_rule_position_target(self):
        if not self.join_for_empty_rule_position_target.arrive():
            return
        self.destroy_position_target()

    def init_position_target__action_destructor(self):
        self.execution_position_target__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.destructor.Destructor
            ),
            self.scheduler,
        )
        self.execution_position_target__action_destructor.guarantees.global_position_empty.consumers.append(
            self.destroy_position_target
        )
        self.execution_position_target__action_destructor.guarantees.global_position_occupied_last.consumers.append(
            self.destroy_position_target
        )
        self.execution_position_target__action_destructor.guarantees.global_position_occupied_first__global_position_transitive.consumers.append(
            self.destroy_position_target
        )

    def destroy_position_target(self):
        if not self.join_for_destroy_position_target.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_target)

    def continue_destroy_position_target(self):
        self.action.get_interface_position(
            "position<target>"
        ).destroy_particle()
        self.guarantees.position_target.publish(
            self.scheduler,
        )
