"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal
from define.runtime import tracing

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.fifth
import local.my_domain_com.my_lib.fifth_destructor
import local.my_domain_com.my_lib.first
import local.my_domain_com.my_lib.first_destructor
import local.my_domain_com.my_lib.fourth_destructor
import local.my_domain_com.my_lib.second_destructor
import local.my_domain_com.my_lib.third
import local.my_domain_com.my_lib.third_destructor


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.first.First,
                local.my_domain_com.my_lib.first_destructor.FirstDestructor,
                local.my_domain_com.my_lib.second_destructor.SecondDestructor,
                local.my_domain_com.my_lib.third.Third,
                local.my_domain_com.my_lib.third_destructor.ThirdDestructor,
                local.my_domain_com.my_lib.fourth_destructor.FourthDestructor,
                local.my_domain_com.my_lib.fifth.Fifth,
                local.my_domain_com.my_lib.fifth_destructor.FifthDestructor,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_action_destroyer: tracing.DestructionConnection
        self.destruction_position_action_destroyer__position_target__global_position_fifth: literal.Position
        self.destruction_position_action_destroyer__position_target__global_position_third: literal.Position
        self.destruction_position_action_destroyer__position_target__global_position_first: literal.Position
        self.join_for_move_position_carrier_to_action_destroyer__position_target = self.scheduler.create_join(3)
        self.destruction_connection_action_destroyer = tracing.DestructionConnection(
            self.scheduler,
            3,
            self.destroy_action_destroyer__position_target__global_position_fifth,
            self.destroy_action_destroyer__position_target__global_position_third,
            self.destroy_action_destroyer__position_target__global_position_first,
        )
        self.execution_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            self.trace_execution,
            "destroyer",
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_target: self.destruction_connection_action_destroyer,
            },
            ),
        )
        self.execution_action_destroyer.join_for_empty_rule_position_target__global_position_first = literal.NO_JOIN
        self.execution_action_destroyer.join_for_empty_rule_position_target__global_position_third = literal.NO_JOIN
        self.execution_action_destroyer.join_for_empty_rule_position_target__global_position_fifth = literal.NO_JOIN
        self.execution_action_destroyer.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_action_destroyer.join_for_destroy_position_target = self.scheduler.create_join(6)

    def on_action_parent_occupied(self):
        self.create_position_carrier()

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier",
            1,
        )
        self.scheduler.submit(self.create_position_carrier__global_position_first)
        self.scheduler.submit(self.create_position_carrier__global_position_third)
        self.create_position_carrier__global_position_fifth()

    def create_position_carrier__global_position_first(self):
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.first.First
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier::/first",
            1,
        )
        self.move_position_carrier_to_action_destroyer__position_target()

    def create_position_carrier__global_position_third(self):
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.third.Third
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier::/third",
            1,
        )
        self.move_position_carrier_to_action_destroyer__position_target()

    def create_position_carrier__global_position_fifth(self):
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.fifth.Fifth
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier::/fifth",
            1,
        )
        self.move_position_carrier_to_action_destroyer__position_target()

    def move_position_carrier_to_action_destroyer__position_target(self):
        if not self.join_for_move_position_carrier_to_action_destroyer__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.scheduler.move_completed(
            self.trace_execution,
            "carrier",
            "/destroyer::target",
            1,
        )
        self.destruction_position_action_destroyer__position_target__global_position_fifth = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.fifth.Fifth
        )
        self.destruction_position_action_destroyer__position_target__global_position_third = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.third.Third
        )
        self.destruction_position_action_destroyer__position_target__global_position_first = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.first.First
        )
        self.execution_action_destroyer.init_when_occupied_position_target()
        self.execution_action_destroyer.execution_position_target__action_first_destructor.join_for_empty_rule_global_position_first = literal.NO_JOIN
        self.execution_action_destroyer.execution_position_target__action_first_destructor.join_for_move_global_position_first_to_position_holder = literal.NO_JOIN
        self.execution_action_destroyer.execution_position_target__action_third_destructor.join_for_empty_rule_global_position_third = literal.NO_JOIN
        self.execution_action_destroyer.execution_position_target__action_third_destructor.join_for_move_global_position_third_to_position_holder = literal.NO_JOIN
        self.execution_action_destroyer.execution_position_target__action_fifth_destructor.join_for_empty_rule_global_position_fifth = literal.NO_JOIN
        self.execution_action_destroyer.execution_position_target__action_fifth_destructor.join_for_move_global_position_fifth_to_position_holder = literal.NO_JOIN
        self.scheduler.submit(self.execution_action_destroyer.accept_when_empty_position_target__global_position_second)
        self.scheduler.submit(self.execution_action_destroyer.accept_when_empty_position_target__global_position_fourth)
        self.scheduler.submit(self.execution_action_destroyer.accept_for_empty_rule_position_target__global_position_first)
        self.scheduler.submit(self.execution_action_destroyer.accept_for_empty_rule_position_target__global_position_third)
        self.scheduler.submit(self.execution_action_destroyer.accept_for_empty_rule_position_target__global_position_fifth)
        self.execution_action_destroyer.accept_when_empty_position_target__global_position_marker()

    def destroy_action_destroyer__position_target__global_position_fifth(self):
        self.destruction_position_action_destroyer__position_target__global_position_fifth.destroy_particle()
        self.scheduler.destroy_completed(
            self.destruction_connection_action_destroyer.trace_execution,
            "target::/fifth",
            1,
        )
        self.destruction_connection_action_destroyer.complete()

    def destroy_action_destroyer__position_target__global_position_third(self):
        self.destruction_position_action_destroyer__position_target__global_position_third.destroy_particle()
        self.scheduler.destroy_completed(
            self.destruction_connection_action_destroyer.trace_execution,
            "target::/third",
            1,
        )
        self.destruction_connection_action_destroyer.complete()

    def destroy_action_destroyer__position_target__global_position_first(self):
        self.destruction_position_action_destroyer__position_target__global_position_first.destroy_particle()
        self.scheduler.destroy_completed(
            self.destruction_connection_action_destroyer.trace_execution,
            "target::/first",
            1,
        )
        self.destruction_connection_action_destroyer.complete()
