"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.construct
import local.my_domain_com.my_lib.marker


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.construct.Construct,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_construct: local.my_domain_com.my_lib.construct.ConstructExecution
        self.destruction_position_position_box__global_position_marker: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_construct = local.my_domain_com.my_lib.construct.ConstructExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.construct.Construct
            ),
            self.scheduler,
        )
        self.execution_position_box__action_construct.guarantees.global_position_marker.inits.append(
            self.init_position_box__action_construct__global_position_marker
        )
        self.execution_position_box__action_construct.guarantees.global_position_marker.consumers.append(
            self.destroy_position_box
        )
        self.execution_position_box__action_construct.guarantees.global_position_marker.consumers.append(
            self.destroy_position_box__global_position_marker
        )
        self.execution_position_box__action_construct.accept_when_empty_global_position_marker()

    def destroy_position_box(self):
        self.local_position_box.destroy_particle()

    def destroy_position_box__global_position_marker(self):
        self.destruction_position_position_box__global_position_marker.destroy_particle()

    def init_position_box__action_construct__global_position_marker(self):
        self.destruction_position_position_box__global_position_marker = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        )
