"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.marker
import local.my_domain_com.my_lib.middle


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_gateway__action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_position_position_gateway__action_middle__position_trigger_pos: literal.Position
        self.join_for_destroy_position_gateway = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_gateway()

    def create_position_gateway(self):
        self.local_position_gateway.create_particle()
        self.execution_position_gateway__action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
        )
        self.execution_position_gateway__action_middle.join_for_empty_rule_position_source = literal.NO_JOIN
        self.execution_position_gateway__action_middle.join_for_move_position_source_to_position_holder = self.scheduler.create_join(2)
        self.execution_position_gateway__action_middle.guarantees.position_source.consumers.append(
            self.destroy_position_gateway
        )
        self.scheduler.submit(self.create_position_gateway__action_middle__position_source)
        self.create_position_gateway__action_middle__position_trigger_pos()

    def create_position_gateway__action_middle__position_source(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<source>"
        ).create_particle()
        self.execution_position_gateway__action_middle.init_when_occupied_position_source()
        self.scheduler.submit(self.create_position_gateway__action_middle__position_source__global_position_marker)
        self.execution_position_gateway__action_middle.continue_when_occupied_position_source()

    def create_position_gateway__action_middle__position_source__global_position_marker(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<source>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        self.execution_position_gateway__action_middle.accept_for_empty_rule_position_source()

    def create_position_gateway__action_middle__position_trigger_pos(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_gateway__action_middle__position_trigger_pos = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_gateway__action_middle__position_trigger_pos.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway(self):
        if not self.join_for_destroy_position_gateway.arrive():
            return
        self.local_position_gateway.destroy_particle()
