"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.origin
import local.my_domain_com.my_lib.target


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_holder = literal.LocalPosition(
            "position<holder>",
            scheduler=self.scheduler,
        )
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.origin.Origin,
                local.my_domain_com.my_lib.target.Target,
            ),
            scheduler=self.scheduler,
        )
        self.destruction_position_position_box__global_position_target: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.origin.Origin
        ).create_particle()
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.origin.Origin
        ).move_particle_to(
            self.local_position_box.particle.get_position(
                local.my_domain_com.my_lib.target.Target
            )
        )
        self.destruction_position_position_box__global_position_target = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.target.Target
        )
        self.destruction_position_position_box__global_position_target.destroy_particle()
        self.local_position_box.move_particle_to(self.local_position_holder)
        self.local_position_holder.destroy_particle()
