"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.inner
import local.my_domain_com.my_lib.source_particle


class Middle(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<gateway>",
                    constraints=(
                        local.my_domain_com.my_lib.inner.Inner,
                        local.my_domain_com.my_lib.source_particle.SourceParticle,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleGuarantees:
    def __init__(self):
        self.position_gateway = literal.Guarantee()


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = MiddleGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_position_gateway__action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_position_position_gateway__action_inner__position_destination: literal.Position
        self.destruction_position_position_gateway__action_inner__position_trigger_pos: literal.Position
        self.join_for_move_position_gateway__global_position_source_particle_to_position_gateway__action_inner__position_source: literal.Join
        self.join_for_destroy_position_gateway: literal.Join
        self.join_for_empty_rule_position_gateway__global_position_source_particle: literal.Join
        self.join_when_empty_position_gateway__action_inner__position_destination: literal.Join
        self.join_for_empty_rule_position_gateway: literal.Join

    def accept_for_empty_rule_position_gateway__global_position_source_particle(self):
        if not self.join_for_empty_rule_position_gateway__global_position_source_particle.arrive():
            return
        self.move_position_gateway__global_position_source_particle_to_position_gateway__action_inner__position_source()

    def accept_when_occupied_position_gateway(self):
        self.execution_position_gateway__action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.action.get_interface_position(
                "position<gateway>"
            ).particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ),
            self.scheduler,
        )
        self.execution_position_gateway__action_inner.join_for_move_position_source_to_position_destination = literal.NO_JOIN
        self.execution_position_gateway__action_inner.guarantees.position_destination__global_position_child.inits.append(
            self.init_position_gateway__action_inner__position_destination__global_position_child
        )
        self.execution_position_gateway__action_inner.guarantees.position_destination__global_position_child.consumers.append(
            self.destroy_position_gateway__action_inner__position_destination
        )

        self.continue_when_occupied_position_gateway()

    def init_when_occupied_position_gateway(self):
        self.execution_position_gateway__action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.action.get_interface_position(
                "position<gateway>"
            ).particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ),
            self.scheduler,
        )
        self.execution_position_gateway__action_inner.join_for_move_position_source_to_position_destination = literal.NO_JOIN
        self.execution_position_gateway__action_inner.guarantees.position_destination__global_position_child.inits.append(
            self.init_position_gateway__action_inner__position_destination__global_position_child
        )
        self.execution_position_gateway__action_inner.guarantees.position_destination__global_position_child.consumers.append(
            self.destroy_position_gateway__action_inner__position_destination
        )

    def continue_when_occupied_position_gateway(self):
        self.create_position_gateway__action_inner__position_trigger_pos()

    def accept_when_empty_position_gateway__action_inner__position_destination(self):
        if not self.join_when_empty_position_gateway__action_inner__position_destination.arrive():
            return
        self.execution_position_gateway__action_inner.accept_for_empty_rule_position_source()

    def accept_for_empty_rule_position_gateway(self):
        if not self.join_for_empty_rule_position_gateway.arrive():
            return
        self.destroy_position_gateway()

    def move_position_gateway__global_position_source_particle_to_position_gateway__action_inner__position_source(self):
        if not self.join_for_move_position_gateway__global_position_source_particle_to_position_gateway__action_inner__position_source.arrive():
            return
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_position(
            local.my_domain_com.my_lib.source_particle.SourceParticle
        ).move_particle_to(
            self.action.get_interface_position(
                "position<gateway>"
            ).particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<source>"
            )
        )
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<source>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.execution_position_gateway__action_inner.accept_for_empty_rule_position_source()

    def create_position_gateway__action_inner__position_trigger_pos(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_gateway__action_inner__position_trigger_pos = self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_gateway__action_inner__position_trigger_pos.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway__action_inner__position_destination(self):
        literal.continue_destruction(self.continue_destroy_position_gateway__action_inner__position_destination)

    def continue_destroy_position_gateway__action_inner__position_destination(self):
        self.destruction_position_position_gateway__action_inner__position_destination.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway(self):
        if not self.join_for_destroy_position_gateway.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_gateway)

    def continue_destroy_position_gateway(self):
        self.action.get_interface_position(
            "position<gateway>"
        ).destroy_particle()
        self.guarantees.position_gateway.publish(
            self.scheduler,
        )

    def init_position_gateway__action_inner__position_destination__global_position_child(self):
        self.destruction_position_position_gateway__action_inner__position_destination = self.action.get_interface_position(
            "position<gateway>"
        ).particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<destination>"
        )
