"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.callee


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.callee.Callee,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_carrier__action_callee: local.my_domain_com.my_lib.callee.CalleeExecution
        self.destruction_position_position_carrier__action_callee__position_trigger_pos: literal.Position
        self.join_for_destroy_position_carrier = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_carrier()

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier",
            1,
        )
        self.execution_position_carrier__action_callee = local.my_domain_com.my_lib.callee.CalleeExecution(
            self.local_position_carrier.particle.get_action(
                local.my_domain_com.my_lib.callee.Callee
            ),
            self.scheduler,
            self.trace_execution,
            "callee",
        )
        self.execution_position_carrier__action_callee.join_for_empty_rule_position_src = literal.NO_JOIN
        self.execution_position_carrier__action_callee.join_for_destroy_position_src = literal.NO_JOIN
        self.execution_position_carrier__action_callee.guarantees.position_src.consumers.append(
            self.destroy_position_carrier
        )
        self.scheduler.submit(self.create_position_carrier__action_callee__position_src)
        self.create_position_carrier__action_callee__position_trigger_pos()

    def create_position_carrier__action_callee__position_src(self):
        self.local_position_carrier.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<src>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier::/callee::src",
            1,
        )
        self.execution_position_carrier__action_callee.init_position_src__action_destructor()
        self.execution_position_carrier__action_callee.accept_when_empty_position_src__global_position_marker()

    def create_position_carrier__action_callee__position_trigger_pos(self):
        self.local_position_carrier.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "carrier::/callee::trigger_pos",
            1,
        )
        self.destruction_position_position_carrier__action_callee__position_trigger_pos = self.local_position_carrier.particle.get_action(
            local.my_domain_com.my_lib.callee.Callee
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_carrier__action_callee__position_trigger_pos.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "carrier::/callee::trigger_pos",
            1,
        )
        self.destroy_position_carrier()

    def destroy_position_carrier(self):
        if not self.join_for_destroy_position_carrier.arrive():
            return
        self.local_position_carrier.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "carrier",
            1,
        )
