"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destination
import local.my_domain_com.my_lib.other


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.other.Other,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_gateway__action_other: local.my_domain_com.my_lib.other.OtherExecution
        self.destruction_position_position_gateway__action_other__position_box: literal.Position
        self.destruction_position_position_gateway__action_other__position_box__global_position_destination: literal.Position
        self.destruction_position_position_gateway__action_other__position_trigger_pos: literal.Position
        self.join_for_destroy_position_gateway = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_gateway()

    def create_position_gateway(self):
        self.local_position_gateway.create_particle()
        self.execution_position_gateway__action_other = local.my_domain_com.my_lib.other.OtherExecution(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.other.Other
            ),
            self.scheduler,
        )
        self.execution_position_gateway__action_other.join_when_empty_position_box__global_position_destination = literal.NO_JOIN
        self.execution_position_gateway__action_other.join_for_move_position_box__global_position_item_to_position_box__global_position_destination = literal.NO_JOIN
        self.execution_position_gateway__action_other.guarantees.position_box__global_position_item__move__position_box__global_position_destination.inits.append(
            self.init_position_gateway__action_other__position_box__global_position_item__move__position_box__global_position_destination
        )
        self.execution_position_gateway__action_other.guarantees.position_box__global_position_item__move__position_box__global_position_destination.consumers.append(
            self.destroy_position_gateway__action_other__position_box
        )
        self.execution_position_gateway__action_other.guarantees.position_box__global_position_item__move__position_box__global_position_destination.consumers.append(
            self.destroy_position_gateway__action_other__position_box__global_position_destination
        )
        self.scheduler.submit(self.create_position_gateway__action_other__position_box)
        self.create_position_gateway__action_other__position_trigger_pos()

    def create_position_gateway__action_other__position_box(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<box>"
        ).create_particle()
        self.execution_position_gateway__action_other.accept_when_empty_position_box__global_position_item()

    def create_position_gateway__action_other__position_trigger_pos(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_gateway__action_other__position_trigger_pos = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_gateway__action_other__position_trigger_pos.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway__action_other__position_box(self):
        self.destruction_position_position_gateway__action_other__position_box.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway__action_other__position_box__global_position_destination(self):
        self.destruction_position_position_gateway__action_other__position_box__global_position_destination.destroy_particle()

    def destroy_position_gateway(self):
        if not self.join_for_destroy_position_gateway.arrive():
            return
        self.local_position_gateway.destroy_particle()

    def init_position_gateway__action_other__position_box__global_position_item__move__position_box__global_position_destination(self):
        self.destruction_position_position_gateway__action_other__position_box = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<box>"
        )
        self.destruction_position_position_gateway__action_other__position_box__global_position_destination = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<box>"
        ).particle.get_position(
            local.my_domain_com.my_lib.destination.Destination
        )
