"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.middle


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_gateway__action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_position_position_gateway__action_middle__position_trigger_pos: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_gateway()

    def create_position_gateway(self):
        self.local_position_gateway.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway",
            1,
        )
        self.execution_position_gateway__action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
            self.trace_execution,
            "middle",
        )
        self.scheduler.submit(self.create_position_gateway__action_middle__position_trigger_pos)
        self.execution_position_gateway__action_middle.on_action_parent_occupied()

    def create_position_gateway__action_middle__position_trigger_pos(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gateway::/middle::trigger_pos",
            1,
        )
        self.destruction_position_position_gateway__action_middle__position_trigger_pos = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_gateway__action_middle__position_trigger_pos.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gateway::/middle::trigger_pos",
            1,
        )
        self.local_position_gateway.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gateway",
            1,
        )
