"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_basket = literal.LocalPosition(
            "position<basket>",
            scheduler=self.scheduler,
        )
        self.local_position_crate = literal.LocalPosition(
            "position<crate>",
            scheduler=self.scheduler,
        )
        self.destruction_position_position_crate__global_position_child: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.local_position_box.move_particle_to(self.local_position_basket)
        self.local_position_basket.move_particle_to(self.local_position_crate)
        self.destruction_position_position_crate__global_position_child = self.local_position_crate.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.scheduler.submit(self.destroy_position_crate)
        self.destroy_position_crate__global_position_child()

    def destroy_position_crate(self):
        self.local_position_crate.destroy_particle()

    def destroy_position_crate__global_position_child(self):
        self.destruction_position_position_crate__global_position_child.destroy_particle()
