"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.make_thing


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.make_thing.MakeThing,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_make_thing: local.my_domain_com.my_lib.make_thing.MakeThingExecution
        self.execution_position_box__action_make_thing__position_result__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.destruction_position_position_box__action_make_thing__position_result: literal.Position
        self.destruction_position_position_box__action_make_thing__position_run: literal.Position
        self.join_for_destroy_position_box = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_make_thing = local.my_domain_com.my_lib.make_thing.MakeThingExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.make_thing.MakeThing
            ),
            self.scheduler,
        )
        self.execution_position_box__action_make_thing.join_when_empty_position_result = literal.NO_JOIN
        self.execution_position_box__action_make_thing.join_for_move_position_temp_to_position_result = literal.NO_JOIN
        self.execution_position_box__action_make_thing.guarantees.position_result.inits.append(
            self.init_position_box__action_make_thing__position_result
        )
        self.execution_position_box__action_make_thing.guarantees.position_result.consumers.append(
            self.destroy_position_box__action_make_thing__position_result
        )
        self.scheduler.submit(self.create_position_box__action_make_thing__position_run)
        self.execution_position_box__action_make_thing.on_action_parent_occupied()

    def create_position_box__action_make_thing__position_run(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.make_thing.MakeThing
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_position_position_box__action_make_thing__position_run = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.make_thing.MakeThing
        ).get_interface_position(
            "position<run>"
        )
        self.scheduler.submit(self.destroy_position_box)
        self.destroy_position_box__action_make_thing__position_run()

    def destroy_position_box__action_make_thing__position_result(self):
        self.destruction_position_position_box__action_make_thing__position_result.destroy_particle()
        self.destroy_position_box()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()

    def destroy_position_box__action_make_thing__position_run(self):
        self.destruction_position_position_box__action_make_thing__position_run.destroy_particle()

    def init_position_box__action_make_thing__position_result(self):
        self.destruction_position_position_box__action_make_thing__position_result = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.make_thing.MakeThing
        ).get_interface_position(
            "position<result>"
        )
        self.execution_position_box__action_make_thing__position_result__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
        )
        self.execution_position_box__action_make_thing.guarantees.position_result.consumers.append(
            self.accept_guarantee_position_box__action_make_thing__position_result__action_destructor
        )

    def accept_guarantee_position_box__action_make_thing__position_result__action_destructor(self):
        self.execution_position_box__action_make_thing__position_result__action_destructor.on_action_parent_occupied()
