"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.runner


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.runner.Runner,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.execution_action_runner: local.my_domain_com.my_lib.runner.RunnerExecution
        self.destruction_position_action_runner__position_run: literal.Position
        self.execution_action_runner = local.my_domain_com.my_lib.runner.RunnerExecution(
            self.scheduler,
            self.trace_execution,
            "runner",
        )

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_runner__position_run)
        self.execution_action_runner.on_action_parent_occupied()

    def create_action_runner__position_run(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.runner.Runner
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/runner::run",
            1,
        )
        self.destruction_position_action_runner__position_run = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.runner.Runner
        ).get_interface_position(
            "position<run>"
        )
        self.destruction_position_action_runner__position_run.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/runner::run",
            1,
        )
