"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.act
import local.my_domain_com.my_lib.end
import local.my_domain_com.my_lib.mid


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.act.Act,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_act: local.my_domain_com.my_lib.act.ActExecution
        self.execution_action_act = local.my_domain_com.my_lib.act.ActExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.act.Act
            ),
            self.scheduler,
        )
        self.execution_action_act.join_for_empty_rule_position_chain_src__global_position_mid__global_position_end = literal.NO_JOIN
        self.execution_action_act.join_for_empty_rule_position_chain_src = literal.NO_JOIN
        self.execution_action_act.join_for_empty_rule_position_chain_src__global_position_mid = literal.NO_JOIN
        self.execution_action_act.join_for_empty_rule_position_trigger = literal.NO_JOIN
        self.execution_action_act.join_for_destroy_position_chain_src__global_position_mid__global_position_end = literal.NO_JOIN
        self.execution_action_act.join_for_destroy_position_chain_src = literal.NO_JOIN
        self.execution_action_act.join_for_destroy_position_chain_src__global_position_mid = literal.NO_JOIN
        self.execution_action_act.join_for_destroy_position_trigger = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_act__position_chain_src)
        self.create_action_act__position_trigger()

    def create_action_act__position_chain_src(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.act.Act
        ).get_interface_position(
            "position<chain_src>"
        ).create_particle()
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.act.Act
        ).get_interface_position(
            "position<chain_src>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid.Mid
        ).create_particle()
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.act.Act
        ).get_interface_position(
            "position<chain_src>"
        ).particle.get_position(
            local.my_domain_com.my_lib.mid.Mid
        ).particle.get_position(
            local.my_domain_com.my_lib.end.End
        ).create_particle()
        self.execution_action_act.accept_for_empty_rule_position_chain_src__global_position_mid__global_position_end()

    def create_action_act__position_trigger(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.act.Act
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        self.execution_action_act.accept_for_empty_rule_position_trigger()
