"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.outer
import local.my_domain_com.my_lib.slot


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.slot.Slot,
        local.my_domain_com.my_lib.outer.Outer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        scheduler.submit(execution.accept_when_empty_global_position_slot)
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_outer: local.my_domain_com.my_lib.outer.OuterExecution
        self.destruction_position_action_outer__position_trigger_pos: literal.Position
        self.execution_action_outer = local.my_domain_com.my_lib.outer.OuterExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ),
            self.scheduler,
        )
        self.execution_action_outer.join_for_empty_rule_global_position_slot = literal.NO_JOIN
        self.execution_action_outer.join_for_destroy_global_position_slot = literal.NO_JOIN

    def accept_when_empty_global_position_slot(self):
        self.create_global_position_slot()

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_outer__position_trigger_pos)
        self.execution_action_outer.on_action_parent_occupied()

    def create_global_position_slot(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.slot.Slot
        ).create_particle()
        self.execution_action_outer.accept_for_empty_rule_global_position_slot()

    def create_action_outer__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_outer__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_outer__position_trigger_pos.destroy_particle()
