"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.leaf


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_destination = literal.LocalPosition(
            "position<destination>",
            scheduler=self.scheduler,
        )
        self.destruction_position_position_box__global_position_child: literal.Position
        self.destruction_position_position_box__global_position_child__global_position_leaf: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box",
            1,
        )
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box::/child",
            1,
        )
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.leaf.Leaf
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box::/child::/leaf",
            1,
        )
        self.destruction_position_position_box__global_position_child = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.destruction_position_position_box__global_position_child__global_position_leaf = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).particle.get_position(
            local.my_domain_com.my_lib.leaf.Leaf
        )
        self.scheduler.submit(self.destroy_position_box__global_position_child)
        self.destroy_position_box__global_position_child__global_position_leaf()

    def destroy_position_box__global_position_child(self):
        self.destruction_position_position_box__global_position_child.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/child",
            1,
        )
        self.local_position_box.move_particle_to(self.local_position_destination)
        self.scheduler.move_completed(
            self.trace_execution,
            "box",
            "destination",
            1,
        )
        self.local_position_destination.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "destination",
            1,
        )

    def destroy_position_box__global_position_child__global_position_leaf(self):
        self.destruction_position_position_box__global_position_child__global_position_leaf.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/child::/leaf",
            1,
        )
