"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destruct_a
import local.my_domain_com.my_lib.destruct_b


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.destruct_a.DestructA,
                local.my_domain_com.my_lib.destruct_b.DestructB,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_destruct_a: local.my_domain_com.my_lib.destruct_a.DestructAExecution
        self.execution_position_box__action_destruct_b: local.my_domain_com.my_lib.destruct_b.DestructBExecution

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_destruct_a = local.my_domain_com.my_lib.destruct_a.DestructAExecution(
            self.scheduler,
        )
        self.execution_position_box__action_destruct_b = local.my_domain_com.my_lib.destruct_b.DestructBExecution(
            self.scheduler,
        )
        self.scheduler.submit(self.destroy_position_box)
        self.scheduler.submit(self.execution_position_box__action_destruct_a.on_action_parent_occupied)
        self.execution_position_box__action_destruct_b.on_action_parent_occupied()

    def destroy_position_box(self):
        self.local_position_box.destroy_particle()
