"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.branch
import local.my_domain_com.my_lib.destroyer


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.destroyer.Destroyer,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.branch.Branch,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_action_destroyer: literal.DestructionConnection
        self.destruction_position_action_destroyer__position_parent__global_position_branch__global_position_b: literal.Position
        self.destruction_position_action_destroyer__position_parent__global_position_branch: literal.Position
        self.destruction_position_action_destroyer__position_parent__global_position_branch__global_position_a: literal.Position
        self.destruction_position_action_destroyer__position_trigger_pos: literal.Position
        self.join_for_move_position_source_to_action_destroyer__position_parent = self.scheduler.create_join(2)
        self.join_for_destroy_action_destroyer__position_parent__global_position_branch = self.scheduler.create_join(2)
        self.destruction_connection_action_destroyer = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_action_destroyer__position_parent__global_position_branch__global_position_b,
            self.destroy_action_destroyer__position_parent__global_position_branch__global_position_a,
        )
        self.execution_action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_parent: self.destruction_connection_action_destroyer,
            },
            ),
        )
        self.execution_action_destroyer.join_for_empty_rule_position_parent = literal.NO_JOIN
        self.execution_action_destroyer.join_for_destroy_position_parent = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_source)
        self.create_action_destroyer__position_trigger_pos()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.branch.Branch
        ).create_particle()
        self.scheduler.submit(self.create_position_source__global_position_branch__global_position_a)
        self.create_position_source__global_position_branch__global_position_b()

    def create_position_source__global_position_branch__global_position_a(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.branch.Branch
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.move_position_source_to_action_destroyer__position_parent()

    def create_position_source__global_position_branch__global_position_b(self):
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.branch.Branch
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).create_particle()
        self.move_position_source_to_action_destroyer__position_parent()

    def move_position_source_to_action_destroyer__position_parent(self):
        if not self.join_for_move_position_source_to_action_destroyer__position_parent.arrive():
            return
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<parent>"
            )
        )
        self.destruction_position_action_destroyer__position_parent__global_position_branch__global_position_b = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<parent>"
        ).particle.get_position(
            local.my_domain_com.my_lib.branch.Branch
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        )
        self.destruction_position_action_destroyer__position_parent__global_position_branch__global_position_a = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<parent>"
        ).particle.get_position(
            local.my_domain_com.my_lib.branch.Branch
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        )
        self.destruction_position_action_destroyer__position_parent__global_position_branch = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<parent>"
        ).particle.get_position(
            local.my_domain_com.my_lib.branch.Branch
        )
        self.execution_action_destroyer.accept_for_empty_rule_position_parent()

    def create_action_destroyer__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_destroyer__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_destroyer__position_trigger_pos.destroy_particle()

    def destroy_action_destroyer__position_parent__global_position_branch__global_position_b(self):
        self.destruction_position_action_destroyer__position_parent__global_position_branch__global_position_b.destroy_particle()
        self.destroy_action_destroyer__position_parent__global_position_branch()

    def destroy_action_destroyer__position_parent__global_position_branch__global_position_a(self):
        self.destruction_position_action_destroyer__position_parent__global_position_branch__global_position_a.destroy_particle()
        self.destroy_action_destroyer__position_parent__global_position_branch()

    def destroy_action_destroyer__position_parent__global_position_branch(self):
        if not self.join_for_destroy_action_destroyer__position_parent__global_position_branch.arrive():
            return
        self.destruction_position_action_destroyer__position_parent__global_position_branch.destroy_particle()
        self.destruction_connection_action_destroyer.complete()
