"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.destructor
import local.my_domain_com.my_lib.marker


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
            None,
            "test",
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.marker.Marker,
                local.my_domain_com.my_lib.destructor.Destructor,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.destruction_position_position_box__global_position_marker: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box",
            1,
        )
        self.execution_position_box__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.destructor.Destructor
            ),
            self.scheduler,
            self.trace_execution,
            "destructor",
        )
        self.execution_position_box__action_destructor.execution_action_forwarder.execution_action_filler.join_for_empty_rule_global_position_marker = literal.NO_JOIN
        self.execution_position_box__action_destructor.execution_action_forwarder.execution_action_filler.join_for_move_global_position_marker_to_position_holder = literal.NO_JOIN
        self.execution_position_box__action_destructor.execution_action_forwarder.join_for_empty_rule_global_position_marker = literal.NO_JOIN
        self.execution_position_box__action_destructor.join_for_empty_rule_global_position_marker = literal.NO_JOIN
        self.execution_position_box__action_destructor.execution_action_forwarder.execution_action_filler.guarantees.global_position_marker.inits.append(
            self.init_position_box__action_destructor__action_forwarder__action_filler__global_position_marker
        )
        self.execution_position_box__action_destructor.execution_action_forwarder.execution_action_filler.guarantees.global_position_marker.consumers.append(
            self.destroy_position_box
        )
        self.execution_position_box__action_destructor.execution_action_forwarder.execution_action_filler.guarantees.global_position_marker.consumers.append(
            self.destroy_position_box__global_position_marker
        )
        self.scheduler.submit(self.create_position_box__global_position_marker)
        self.execution_position_box__action_destructor.on_action_parent_occupied()

    def create_position_box__global_position_marker(self):
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "box::/marker",
            1,
        )
        self.execution_position_box__action_destructor.accept_for_empty_rule_global_position_marker()

    def destroy_position_box(self):
        self.local_position_box.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box",
            1,
        )

    def destroy_position_box__global_position_marker(self):
        self.destruction_position_position_box__global_position_marker.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "box::/marker",
            1,
        )

    def init_position_box__action_destructor__action_forwarder__action_filler__global_position_marker(self):
        self.destruction_position_position_box__global_position_marker = self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        )
