"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.b
import local.my_domain_com.my_lib.other


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_gateway = literal.LocalPosition(
            "position<gateway>",
            constraints=(
                local.my_domain_com.my_lib.other.Other,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_gateway__action_other: local.my_domain_com.my_lib.other.OtherExecution
        self.destruction_position_position_gateway__action_other__position_holder: literal.Position
        self.destruction_position_position_gateway__action_other__position_holder__global_position_a: literal.Position
        self.destruction_position_position_gateway__action_other__position_holder__global_position_b: literal.Position
        self.destruction_position_position_gateway__action_other__position_trigger_pos: literal.Position
        self.join_for_destroy_position_gateway = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_gateway()

    def create_position_gateway(self):
        self.local_position_gateway.create_particle()
        self.execution_position_gateway__action_other = local.my_domain_com.my_lib.other.OtherExecution(
            self.local_position_gateway.particle.get_action(
                local.my_domain_com.my_lib.other.Other
            ),
            self.scheduler,
        )
        self.execution_position_gateway__action_other.join_for_empty_rule_position_source = self.scheduler.create_join(2)
        self.execution_position_gateway__action_other.join_for_move_position_source_to_position_holder = literal.NO_JOIN
        self.execution_position_gateway__action_other.guarantees.position_source__move__position_holder.inits.append(
            self.init_position_gateway__action_other__position_source__move__position_holder
        )
        self.execution_position_gateway__action_other.guarantees.position_source__move__position_holder.consumers.append(
            self.destroy_position_gateway__action_other__position_holder
        )
        self.execution_position_gateway__action_other.guarantees.position_source__move__position_holder.consumers.append(
            self.destroy_position_gateway__action_other__position_holder__global_position_a
        )
        self.execution_position_gateway__action_other.guarantees.position_source__move__position_holder.consumers.append(
            self.destroy_position_gateway__action_other__position_holder__global_position_b
        )
        self.scheduler.submit(self.create_position_gateway__action_other__position_source)
        self.create_position_gateway__action_other__position_trigger_pos()

    def create_position_gateway__action_other__position_source(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<source>"
        ).create_particle()
        self.scheduler.submit(self.create_position_gateway__action_other__position_source__global_position_a)
        self.create_position_gateway__action_other__position_source__global_position_b()

    def create_position_gateway__action_other__position_source__global_position_a(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<source>"
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.execution_position_gateway__action_other.accept_for_empty_rule_position_source()

    def create_position_gateway__action_other__position_source__global_position_b(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<source>"
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        ).create_particle()
        self.execution_position_gateway__action_other.accept_for_empty_rule_position_source()

    def create_position_gateway__action_other__position_trigger_pos(self):
        self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_gateway__action_other__position_trigger_pos = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_gateway__action_other__position_trigger_pos.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway__action_other__position_holder(self):
        self.destruction_position_position_gateway__action_other__position_holder.destroy_particle()
        self.destroy_position_gateway()

    def destroy_position_gateway__action_other__position_holder__global_position_a(self):
        self.destruction_position_position_gateway__action_other__position_holder__global_position_a.destroy_particle()

    def destroy_position_gateway__action_other__position_holder__global_position_b(self):
        self.destruction_position_position_gateway__action_other__position_holder__global_position_b.destroy_particle()

    def destroy_position_gateway(self):
        if not self.join_for_destroy_position_gateway.arrive():
            return
        self.local_position_gateway.destroy_particle()

    def init_position_gateway__action_other__position_source__move__position_holder(self):
        self.destruction_position_position_gateway__action_other__position_holder = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<holder>"
        )
        self.destruction_position_position_gateway__action_other__position_holder__global_position_a = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<holder>"
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        )
        self.destruction_position_position_gateway__action_other__position_holder__global_position_b = self.local_position_gateway.particle.get_action(
            local.my_domain_com.my_lib.other.Other
        ).get_interface_position(
            "position<holder>"
        ).particle.get_position(
            local.my_domain_com.my_lib.b.B
        )
