"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.filler


class Forwarder(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.filler.Filler,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class ForwarderGuarantees:
    def __init__(self):
        self.position_trigger_pos = literal.Guarantee()


@final
class ForwarderExecution:
    def __init__(
        self,
        action: Forwarder,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = ForwarderGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_action_filler: local.my_domain_com.my_lib.filler.FillerExecution
        self.join_for_destroy_position_trigger_pos: literal.Join
        self.join_for_empty_rule_position_trigger_pos: literal.Join
        self.join_for_empty_rule_global_position_marker: literal.Join
        self.execution_action_filler = local.my_domain_com.my_lib.filler.FillerExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.filler.Filler
            ),
            self.scheduler,
        )
        self.execution_action_filler.join_for_empty_rule_position_trigger_pos = literal.NO_JOIN
        self.execution_action_filler.join_for_destroy_position_trigger_pos = literal.NO_JOIN

    def on_action_parent_occupied(self):
        self.create_action_filler__position_trigger_pos()

    def accept_for_empty_rule_position_trigger_pos(self):
        if not self.join_for_empty_rule_position_trigger_pos.arrive():
            return
        self.destroy_position_trigger_pos()

    def accept_for_empty_rule_global_position_marker(self):
        if not self.join_for_empty_rule_global_position_marker.arrive():
            return
        self.execution_action_filler.accept_for_empty_rule_global_position_marker()

    def create_action_filler__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.filler.Filler
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.execution_action_filler.accept_for_empty_rule_position_trigger_pos()

    def destroy_position_trigger_pos(self):
        if not self.join_for_destroy_position_trigger_pos.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_trigger_pos)

    def continue_destroy_position_trigger_pos(self):
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.guarantees.position_trigger_pos.publish(
            self.scheduler,
        )
