"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.beep
import local.my_domain_com.my_lib.destructor


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.destructor.Destructor,
                local.my_domain_com.my_lib.beep.Beep,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_beep: local.my_domain_com.my_lib.beep.BeepExecution
        self.execution_position_box__action_destructor: local.my_domain_com.my_lib.destructor.DestructorExecution
        self.destruction_position_position_box__action_beep__position_trigger: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_beep = local.my_domain_com.my_lib.beep.BeepExecution(
            self.scheduler,
        )
        self.execution_position_box__action_destructor = local.my_domain_com.my_lib.destructor.DestructorExecution(
            self.scheduler,
        )
        self.scheduler.submit(self.create_position_box__action_beep__position_trigger)
        self.scheduler.submit(self.execution_position_box__action_beep.on_action_parent_occupied)
        self.execution_position_box__action_destructor.on_action_parent_occupied()

    def create_position_box__action_beep__position_trigger(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.beep.Beep
        ).get_interface_position(
            "position<trigger>"
        ).create_particle()
        self.destruction_position_position_box__action_beep__position_trigger = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.beep.Beep
        ).get_interface_position(
            "position<trigger>"
        )
        self.scheduler.submit(self.destroy_position_box)
        self.destroy_position_box__action_beep__position_trigger()

    def destroy_position_box(self):
        self.local_position_box.destroy_particle()

    def destroy_position_box__action_beep__position_trigger(self):
        self.destruction_position_position_box__action_beep__position_trigger.destroy_particle()
