"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.earlier_assigned_destructor
import local.my_domain_com.my_lib.later_assigned_destructor
import local.my_domain_com.my_lib.marker


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<target>",
                    constraints=(
                        local.my_domain_com.my_lib.earlier_assigned_destructor.EarlierAssignedDestructor,
                        local.my_domain_com.my_lib.later_assigned_destructor.LaterAssignedDestructor,
                        local.my_domain_com.my_lib.marker.Marker,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.position_target = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_position_target__action_earlier_assigned_destructor: local.my_domain_com.my_lib.earlier_assigned_destructor.EarlierAssignedDestructorExecution
        self.execution_position_target__action_later_assigned_destructor: local.my_domain_com.my_lib.later_assigned_destructor.LaterAssignedDestructorExecution
        self.destruction_position_position_target__global_position_marker: literal.Position
        self.join_for_destroy_position_target: literal.Join
        self.join_for_empty_rule_position_target: literal.Join

    def accept_when_empty_position_target__global_position_marker(self):
        self.create_position_target__global_position_marker()

    def accept_for_empty_rule_position_target(self):
        if not self.join_for_empty_rule_position_target.arrive():
            return
        self.destroy_position_target()

    def init_when_occupied_position_target(self):
        self.execution_position_target__action_earlier_assigned_destructor = local.my_domain_com.my_lib.earlier_assigned_destructor.EarlierAssignedDestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.earlier_assigned_destructor.EarlierAssignedDestructor
            ),
            self.scheduler,
            self.trace_execution,
            "earlier_assigned_destructor",
        )
        self.execution_position_target__action_earlier_assigned_destructor.guarantees.global_position_marker.consumers.append(
            self.accept_guarantee_position_target__action_later_assigned_destructor
        )
        self.execution_position_target__action_later_assigned_destructor = local.my_domain_com.my_lib.later_assigned_destructor.LaterAssignedDestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.later_assigned_destructor.LaterAssignedDestructor
            ),
            self.scheduler,
            self.trace_execution,
            "later_assigned_destructor",
        )
        self.execution_position_target__action_later_assigned_destructor.guarantees.global_position_marker.consumers.append(
            self.destroy_position_target
        )

    def create_position_target__global_position_marker(self):
        self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "target::/marker",
            1,
        )
        self.destruction_position_position_target__global_position_marker = self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        )
        self.destruction_position_position_target__global_position_marker.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "target::/marker",
            1,
        )
        self.execution_position_target__action_earlier_assigned_destructor.accept_when_empty_global_position_marker()

    def destroy_position_target(self):
        if not self.join_for_destroy_position_target.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_target)

    def continue_destroy_position_target(self):
        self.action.get_interface_position(
            "position<target>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "target",
            1,
        )
        self.guarantees.position_target.publish(
            self.scheduler,
        )

    def accept_guarantee_position_target__action_later_assigned_destructor(self):
        self.execution_position_target__action_later_assigned_destructor.accept_when_empty_global_position_marker()
