load("@aspect_rules_py//py:defs.bzl", "py_library")
load("//tools/bzl:format.bzl", "format_test")
load("//tools/bzl:py_test.bzl", "py_test")
load("//tools/bzl:pyright.bzl", "pyright_test")

py_test(
    name = "action_contract_test",
    size = "small",
    srcs = ["action_contract_test.py"],
    deps = [
        ":action_contract",
        "//define/compiler:ast",
        "//define/compiler/validator:test_helpers",
        "//define/compiler/validator/structural:program_validator",
    ],
)

py_library(
    name = "action_contract",
    srcs = ["action_contract.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":operation_graph_model",
        ":quality_assignment",
        "//define/compiler:ast",
    ],
)

py_library(
    name = "definition_postorder_validator",
    srcs = ["definition_postorder_validator.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":action_contract",
        ":operation_graph",
        ":operation_graph_model",
        ":particle_info",
        ":particle_operation_validator",
        ":particle_tracker",
        ":quality_assignment",
        ":reference_graph_validation_state",
        ":requirement_violation",
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/graphs:action_call_graph",
        "//define/compiler/validator:scope_tracker",
        "//define/compiler/validator:validation_result",
        "//define/compiler/validator/reference_graph/dead_code:dead_constraint_tracker",
    ],
)

py_library(
    name = "operation_graph",
    srcs = ["operation_graph.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":action_contract",
        ":operation_graph_model",
        ":operation_graph_rules",
        "//define/compiler:ast",
        "//define/compiler/data_structures:typed_name_dict",
    ],
)

py_library(
    name = "operation_graph_action_resolver",
    srcs = ["operation_graph_action_resolver.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":operation_graph",
        ":operation_graph_model",
        ":operation_graph_rules",
        "//define/compiler:ast",
        "//define/compiler/data_structures:typed_name_dict",
    ],
)

py_library(
    name = "operation_graph_labeler",
    srcs = ["operation_graph_labeler.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":operation_graph",
        ":operation_graph_model",
        ":operation_graph_resolver",
        "//define/compiler:ast",
        "//define/compiler/data_structures:typed_name_dict",
    ],
)

py_test(
    name = "operation_graph_labeler_test",
    size = "small",
    srcs = ["operation_graph_labeler_test.py"],
    deps = [
        ":operation_graph_labeler",
        ":operation_graph_resolver",
        "//define/compiler:conftest",
        "//define/compiler/validator:test_helpers",
    ],
)

py_library(
    name = "operation_graph_model",
    srcs = ["operation_graph_model.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = ["//define/compiler:ast"],
)

py_library(
    name = "operation_graph_rules",
    srcs = ["operation_graph_rules.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":operation_graph_model",
        "//define/compiler:ast",
    ],
)

py_test(
    name = "operation_graph_rules_test",
    size = "small",
    srcs = ["operation_graph_rules_test.py"],
    deps = [
        ":operation_graph_model",
        ":operation_graph_rules",
        "//define/compiler:ast",
    ],
)

py_library(
    name = "operation_graph_renderer",
    testonly = True,
    srcs = ["operation_graph_renderer.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":operation_graph",
        ":operation_graph_labeler",
        ":operation_graph_resolver",
    ],
)

py_test(
    name = "operation_graph_renderer_test",
    size = "small",
    srcs = ["operation_graph_renderer_test.py"],
    deps = [
        ":operation_graph_renderer",
        "@pypi//pytest",
    ],
)

py_library(
    name = "operation_graph_resolver",
    srcs = ["operation_graph_resolver.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":operation_graph",
        ":operation_graph_action_resolver",
        ":operation_graph_model",
        "//define/compiler:ast",
    ],
)

py_test(
    name = "operation_graph_resolver_test",
    size = "small",
    srcs = ["operation_graph_resolver_test.py"],
    deps = [
        ":operation_graph",
        ":operation_graph_resolver",
        "//define/compiler:ast",
    ],
)

py_test(
    name = "operation_graph_test",
    size = "small",
    srcs = ["operation_graph_test.py"],
    deps = [
        ":operation_graph_model",
        "//define/compiler:ast",
    ],
)

py_library(
    name = "particle_info",
    srcs = ["particle_info.py"],
    visibility = ["//define/compiler/validator/reference_graph:__subpackages__"],
    deps = [
        ":quality_assignment",
        "//define/compiler:ast",
    ],
)

py_library(
    name = "particle_operation_validator",
    srcs = ["particle_operation_validator.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":particle_tracker",
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
    ],
)

py_library(
    name = "particle_tracker",
    srcs = ["particle_tracker.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":action_contract",
        ":operation_graph",
        ":operation_graph_model",
        ":particle_info",
        ":quality_assignment",
        "//define/compiler:ast",
        "//define/compiler/data_structures:trie",
        "//define/compiler/validator/reference_graph/dead_code:dead_interface_tracker",
    ],
)

py_library(
    name = "quality_assignment",
    srcs = ["quality_assignment.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        "//define/compiler:ast",
    ],
)

py_test(
    name = "quality_assignment_test",
    size = "small",
    srcs = ["quality_assignment_test.py"],
    deps = [
        ":quality_assignment",
        "//define/compiler:ast",
    ],
)

py_library(
    name = "reference_graph",
    srcs = ["__init__.py"],
)

py_library(
    name = "reference_graph_validation_state",
    srcs = ["reference_graph_validation_state.py"],
    deps = [
        ":action_contract",
        ":quality_assignment",
        "//define/compiler:ast",
    ],
)

py_test(
    name = "reference_graph_validation_state_test",
    size = "small",
    srcs = ["reference_graph_validation_state_test.py"],
    deps = [
        ":action_contract",
        ":quality_assignment",
        ":reference_graph_validation_state",
        "//define/compiler:ast",
    ],
)

py_library(
    name = "reference_graph_validator",
    srcs = ["reference_graph_validator.py"],
    visibility = [
        "//define/compiler:__subpackages__",
        "//tools:__subpackages__",
    ],
    deps = [
        ":action_contract",
        ":definition_postorder_validator",
        ":operation_graph",
        ":reference_graph_validation_state",
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
        "//define/compiler/data_structures:typed_name_dict",
        "//define/compiler/graphs:action_call_graph",
        "//define/compiler/graphs:reference_graph",
        "//define/compiler/graphs:reference_graph_executor",
        "//define/compiler/validator:validation_result",
    ],
)

py_test(
    name = "reference_graph_validator_test",
    size = "small",
    srcs = ["reference_graph_validator_test.py"],
    deps = [
        ":definition_postorder_validator",
        ":reference_graph_validator",
        "//define/compiler/validator:test_helpers",
        "//define/compiler/validator:validation_result",
        "//define/compiler/validator/structural:program_validator",
        "@pypi//pytest",
    ],
)

py_library(
    name = "requirement_violation",
    srcs = ["requirement_violation.py"],
    visibility = ["//define/compiler:__subpackages__"],
    deps = [
        ":action_contract",
        ":particle_info",
        "//define/compiler:ast",
        "//define/compiler:diagnostics",
    ],
)

# --- Format checking ---

format_test(
    name = "format_test",
    srcs = glob(["*.py"]),
    python = "@multitool//tools/ruff",
)

# --- Type-checking ---

pyright_test(
    name = "pyright_test",
    deps = [
        ":action_contract",
        ":action_contract_test",
        ":definition_postorder_validator",
        ":operation_graph",
        ":operation_graph_action_resolver",
        ":operation_graph_labeler",
        ":operation_graph_labeler_test",
        ":operation_graph_model",
        ":operation_graph_renderer",
        ":operation_graph_renderer_test",
        ":operation_graph_resolver",
        ":operation_graph_resolver_test",
        ":operation_graph_rules",
        ":operation_graph_rules_test",
        ":operation_graph_test",
        ":particle_info",
        ":particle_operation_validator",
        ":particle_tracker",
        ":quality_assignment",
        ":quality_assignment_test",
        ":reference_graph",
        ":reference_graph_validation_state",
        ":reference_graph_validation_state_test",
        ":reference_graph_validator",
        ":reference_graph_validator_test",
        ":requirement_violation",
    ],
)
