"""Generated by the Define compiler."""

from typing import ClassVar, final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.triggered


class Test(literal.EntryPoint):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.triggered.Triggered,
    )

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            self,
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        action: Test,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.local_position_source = literal.LocalPosition(
            "position<source>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.execution_action_triggered: local.my_domain_com.my_lib.triggered.TriggeredExecution
        self.destruction_position_action_triggered__position_run: literal.Position
        self.execution_action_triggered = local.my_domain_com.my_lib.triggered.TriggeredExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.triggered.Triggered
            ),
            self.scheduler,
        )
        self.execution_action_triggered.join_for_empty_rule_position_run__global_position_child = literal.NO_JOIN
        self.execution_action_triggered.join_for_destroy_position_run__global_position_child = literal.NO_JOIN
        self.execution_action_triggered.guarantees.position_run__global_position_child.inits.append(
            self.init_action_triggered__position_run__global_position_child
        )
        self.execution_action_triggered.guarantees.position_run__global_position_child.consumers.append(
            self.destroy_action_triggered__position_run
        )

    def on_action_parent_occupied(self):
        self.create_position_source()

    def create_position_source(self):
        self.local_position_source.create_particle()
        self.local_position_source.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.local_position_source.move_particle_to(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.triggered.Triggered
            ).get_interface_position(
                "position<run>"
            )
        )
        self.execution_action_triggered.accept_for_empty_rule_position_run__global_position_child()

    def destroy_action_triggered__position_run(self):
        self.destruction_position_action_triggered__position_run.destroy_particle()

    def init_action_triggered__position_run__global_position_child(self):
        self.destruction_position_action_triggered__position_run = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.triggered.Triggered
        ).get_interface_position(
            "position<run>"
        )
