"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.middle
import local.my_domain_com.my_lib.source_particle


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_position_position_box__action_middle__position_trigger_pos: literal.Position
        self.join_for_destroy_position_box = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
        )
        self.execution_position_box__action_middle.join_for_empty_rule_position_gateway__global_position_source_particle = literal.NO_JOIN
        self.execution_position_box__action_middle.join_when_empty_position_gateway__action_inner__position_destination = literal.NO_JOIN
        self.execution_position_box__action_middle.join_for_empty_rule_position_gateway = literal.NO_JOIN
        self.execution_position_box__action_middle.join_for_move_position_gateway__global_position_source_particle_to_position_gateway__action_inner__position_source = literal.NO_JOIN
        self.execution_position_box__action_middle.join_for_destroy_position_gateway = self.scheduler.create_join(2)
        self.execution_position_box__action_middle.guarantees.position_gateway.consumers.append(
            self.destroy_position_box
        )
        self.scheduler.submit(self.create_position_box__action_middle__position_gateway)
        self.create_position_box__action_middle__position_trigger_pos()

    def create_position_box__action_middle__position_gateway(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gateway>"
        ).create_particle()
        self.execution_position_box__action_middle.init_when_occupied_position_gateway()
        self.execution_position_box__action_middle.execution_position_gateway__action_inner.join_for_empty_rule_position_source = literal.NO_JOIN
        self.scheduler.submit(self.create_position_box__action_middle__position_gateway__global_position_source_particle)
        self.execution_position_box__action_middle.continue_when_occupied_position_gateway()

    def create_position_box__action_middle__position_gateway__global_position_source_particle(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gateway>"
        ).particle.get_position(
            local.my_domain_com.my_lib.source_particle.SourceParticle
        ).create_particle()
        self.execution_position_box__action_middle.accept_for_empty_rule_position_gateway__global_position_source_particle()

    def create_position_box__action_middle__position_trigger_pos(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_box__action_middle__position_trigger_pos = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_box__action_middle__position_trigger_pos.destroy_particle()
        self.destroy_position_box()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()
