"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.holder
import local.my_domain_com.my_lib.middle


class Outer(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.holder.Holder,
        local.my_domain_com.my_lib.middle.Middle,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class OuterExecution:
    def __init__(
        self,
        action: Outer,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.destruction_connections = destruction_connections
        self.execution_action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_position_global_position_holder__global_position_a: literal.Position
        self.destruction_position_action_middle__position_trigger_pos: literal.Position
        self.join_for_destroy_global_position_holder__global_position_a: literal.Join
        self.join_for_empty_rule_global_position_holder__global_position_a: literal.Join
        self.execution_action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.action.on_particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
        )

    def accept_for_empty_rule_global_position_holder__global_position_a(self):
        if not self.join_for_empty_rule_global_position_holder__global_position_a.arrive():
            return
        self.destruction_position_global_position_holder__global_position_a = self.action.on_particle.get_position(
            local.my_domain_com.my_lib.holder.Holder
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        )
        self.destroy_global_position_holder__global_position_a()

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_middle__position_trigger_pos)
        self.execution_action_middle.on_action_parent_occupied()

    def destroy_global_position_holder__global_position_a(self):
        if not self.join_for_destroy_global_position_holder__global_position_a.arrive():
            return
        literal.continue_destruction(self.continue_destroy_global_position_holder__global_position_a)

    def continue_destroy_global_position_holder__global_position_a(self):
        self.destruction_position_global_position_holder__global_position_a.destroy_particle()
        self.execution_action_middle.accept_when_empty_global_position_holder__global_position_a()

    def create_action_middle__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_middle__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_middle__position_trigger_pos.destroy_particle()
