"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.child


class Inner(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<input>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class InnerGuarantees:
    def __init__(self):
        self.position_input = literal.Guarantee()


@final
class InnerExecution:
    def __init__(
        self,
        action: Inner,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = InnerGuarantees()
        self.destruction_connections = destruction_connections
        self.destruction_position_position_input__global_position_child: literal.Position
        self.join_for_destroy_position_input__global_position_child: literal.Join
        self.join_for_destroy_position_input: literal.Join
        self.join_for_empty_rule_position_input__global_position_child: literal.Join
        self.join_for_empty_rule_position_input: literal.Join

    def accept_for_empty_rule_position_input__global_position_child(self):
        if not self.join_for_empty_rule_position_input__global_position_child.arrive():
            return
        self.destruction_position_position_input__global_position_child = self.action.get_interface_position(
            "position<input>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.destroy_position_input__global_position_child()

    def accept_for_empty_rule_position_input(self):
        if not self.join_for_empty_rule_position_input.arrive():
            return
        self.destroy_position_input()

    def destroy_position_input__global_position_child(self):
        if not self.join_for_destroy_position_input__global_position_child.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_input__global_position_child)

    def continue_destroy_position_input__global_position_child(self):
        self.destruction_position_position_input__global_position_child.destroy_particle()
        self.destroy_position_input()

    def destroy_position_input(self):
        if not self.join_for_destroy_position_input.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_input)

    def continue_destroy_position_input(self):
        self.action.get_interface_position(
            "position<input>"
        ).destroy_particle()
        self.guarantees.position_input.publish(
            self.scheduler,
        )
