"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.outer


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.child.Child,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_outer_holder = literal.LocalPosition(
            "position<outer_holder>",
            constraints=(
                local.my_domain_com.my_lib.outer.Outer,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_outer_holder__action_outer: local.my_domain_com.my_lib.outer.OuterExecution
        self.destruction_position_position_outer_holder__action_outer__position_middle_holder: literal.Position
        self.destruction_position_position_outer_holder__action_outer__position_run: literal.Position
        self.join_for_move_position_box_to_position_outer_holder__action_outer__position_input = self.scheduler.create_join(2)
        self.join_for_destroy_position_outer_holder = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_box)
        self.create_position_outer_holder()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.local_position_box.particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).create_particle()
        self.move_position_box_to_position_outer_holder__action_outer__position_input()

    def create_position_outer_holder(self):
        self.local_position_outer_holder.create_particle()
        self.execution_position_outer_holder__action_outer = local.my_domain_com.my_lib.outer.OuterExecution(
            self.local_position_outer_holder.particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ),
            self.scheduler,
        )
        self.execution_position_outer_holder__action_outer.join_for_empty_rule_position_input = literal.NO_JOIN
        self.execution_position_outer_holder__action_outer.join_for_move_position_input_to_position_middle_holder__action_middle__position_input = self.scheduler.create_join(2)
        self.execution_position_outer_holder__action_outer.guarantees.position_middle_holder.inits.append(
            self.register_guarantee_position_inner_holder__action_inner__position_input
        )
        self.scheduler.submit(self.move_position_box_to_position_outer_holder__action_outer__position_input)
        self.scheduler.submit(self.create_position_outer_holder__action_outer__position_run)
        self.execution_position_outer_holder__action_outer.accept_when_empty_position_middle_holder()

    def move_position_box_to_position_outer_holder__action_outer__position_input(self):
        if not self.join_for_move_position_box_to_position_outer_holder__action_outer__position_input.arrive():
            return
        self.local_position_box.move_particle_to(
            self.local_position_outer_holder.particle.get_action(
                local.my_domain_com.my_lib.outer.Outer
            ).get_interface_position(
                "position<input>"
            )
        )
        self.execution_position_outer_holder__action_outer.accept_for_empty_rule_position_input()

    def create_position_outer_holder__action_outer__position_run(self):
        self.local_position_outer_holder.particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_position_position_outer_holder__action_outer__position_run = self.local_position_outer_holder.particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<run>"
        )
        self.destruction_position_position_outer_holder__action_outer__position_run.destroy_particle()
        self.destroy_position_outer_holder()

    def destroy_position_outer_holder__action_outer__position_middle_holder(self):
        self.destruction_position_position_outer_holder__action_outer__position_middle_holder.destroy_particle()
        self.destroy_position_outer_holder()

    def destroy_position_outer_holder(self):
        if not self.join_for_destroy_position_outer_holder.arrive():
            return
        self.local_position_outer_holder.destroy_particle()

    def init_position_outer_holder__action_outer__position_middle_holder__action_middle__position_input(self):
        self.destruction_position_position_outer_holder__action_outer__position_middle_holder = self.local_position_outer_holder.particle.get_action(
            local.my_domain_com.my_lib.outer.Outer
        ).get_interface_position(
            "position<middle_holder>"
        )

    def register_guarantee_position_inner_holder__action_inner__position_input(self):
        self.execution_position_outer_holder__action_outer.execution_position_middle_holder__action_middle.guarantees.position_input.inits.append(
            self.init_position_outer_holder__action_outer__position_middle_holder__action_middle__position_input
        )
        self.execution_position_outer_holder__action_outer.execution_position_middle_holder__action_middle.guarantees.position_input.consumers.append(
            self.destroy_position_outer_holder__action_outer__position_middle_holder
        )
