"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.worker


class Second(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class SecondExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
    ):
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.local_position_gw = literal.LocalPosition(
            "position<gw>",
            constraints=(
                local.my_domain_com.my_lib.worker.Worker,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_gw__action_worker: local.my_domain_com.my_lib.worker.WorkerExecution
        self.execution_position_gw__action_worker_2: local.my_domain_com.my_lib.worker.WorkerExecution
        self.destruction_position_position_gw__action_worker__position_trigger_pos: literal.Position
        self.destruction_position_position_gw__action_worker__position_trigger_pos_2: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_gw()

    def create_position_gw(self):
        self.local_position_gw.create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gw",
            1,
        )
        self.execution_position_gw__action_worker = local.my_domain_com.my_lib.worker.WorkerExecution(
            self.scheduler,
            self.trace_execution,
            "worker",
        )
        self.execution_position_gw__action_worker_2 = local.my_domain_com.my_lib.worker.WorkerExecution(
            self.scheduler,
            self.trace_execution,
            "worker#2",
        )
        self.scheduler.submit(self.create_position_gw__action_worker__position_trigger_pos)
        self.scheduler.submit(self.execution_position_gw__action_worker.on_action_parent_occupied)
        self.execution_position_gw__action_worker_2.on_action_parent_occupied()

    def create_position_gw__action_worker__position_trigger_pos(self):
        self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gw::/worker::trigger_pos",
            1,
        )
        self.destruction_position_position_gw__action_worker__position_trigger_pos = self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_gw__action_worker__position_trigger_pos.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gw::/worker::trigger_pos",
            1,
        )
        self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "gw::/worker::trigger_pos",
            2,
        )
        self.destruction_position_position_gw__action_worker__position_trigger_pos_2 = self.local_position_gw.particle.get_action(
            local.my_domain_com.my_lib.worker.Worker
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.scheduler.submit(self.destroy_position_gw)
        self.destroy_position_gw__action_worker__position_trigger_pos()

    def destroy_position_gw(self):
        self.local_position_gw.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gw",
            1,
        )

    def destroy_position_gw__action_worker__position_trigger_pos(self):
        self.destruction_position_position_gw__action_worker__position_trigger_pos_2.destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "gw::/worker::trigger_pos",
            2,
        )
