"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.child
import local.my_domain_com.my_lib.inner


class Middle(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<input>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                    scheduler=on_particle.scheduler,
                ),
                literal.LocalPosition(
                    "position<run>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleGuarantees:
    def __init__(self):
        self.position_input = literal.Guarantee()


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = MiddleGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_inner_holder = literal.LocalPosition(
            "position<inner_holder>",
            constraints=(
                local.my_domain_com.my_lib.inner.Inner,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_inner_holder__action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_position_position_inner_holder__action_inner__position_run: literal.Position
        self.join_for_move_position_input_to_position_inner_holder__action_inner__position_input: literal.Join
        self.join_for_destroy_position_inner_holder = self.scheduler.create_join(2)
        self.join_for_empty_rule_position_input: literal.Join

    def on_action_parent_occupied(self):
        self.create_position_inner_holder()

    def accept_for_empty_rule_position_input(self):
        if not self.join_for_empty_rule_position_input.arrive():
            return
        self.move_position_input_to_position_inner_holder__action_inner__position_input()

    def create_position_inner_holder(self):
        self.local_position_inner_holder.create_particle()
        self.execution_position_inner_holder__action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.local_position_inner_holder.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ),
            self.scheduler,
            destruction_connections=self.destruction_connections,
        )
        self.execution_position_inner_holder__action_inner.join_for_empty_rule_position_input__global_position_child = literal.NO_JOIN
        self.execution_position_inner_holder__action_inner.join_for_empty_rule_position_input = literal.NO_JOIN
        self.execution_position_inner_holder__action_inner.join_for_destroy_position_input__global_position_child = literal.NO_JOIN
        self.execution_position_inner_holder__action_inner.join_for_destroy_position_input = literal.NO_JOIN
        self.execution_position_inner_holder__action_inner.guarantees.position_input.consumers.append(
            self.destroy_position_inner_holder
        )
        self.scheduler.submit(self.move_position_input_to_position_inner_holder__action_inner__position_input)
        self.create_position_inner_holder__action_inner__position_run()

    def move_position_input_to_position_inner_holder__action_inner__position_input(self):
        if not self.join_for_move_position_input_to_position_inner_holder__action_inner__position_input.arrive():
            return
        self.action.get_interface_position(
            "position<input>"
        ).move_particle_to(
            self.local_position_inner_holder.particle.get_action(
                local.my_domain_com.my_lib.inner.Inner
            ).get_interface_position(
                "position<input>"
            )
        )
        self.guarantees.position_input.publish(
            self.scheduler,
            self.execution_position_inner_holder__action_inner.accept_for_empty_rule_position_input__global_position_child,
        )

    def create_position_inner_holder__action_inner__position_run(self):
        self.local_position_inner_holder.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<run>"
        ).create_particle()
        self.destruction_position_position_inner_holder__action_inner__position_run = self.local_position_inner_holder.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<run>"
        )
        self.scheduler.submit(self.destroy_position_inner_holder)
        self.destroy_position_inner_holder__action_inner__position_run()

    def destroy_position_inner_holder(self):
        if not self.join_for_destroy_position_inner_holder.arrive():
            return
        self.local_position_inner_holder.destroy_particle()

    def destroy_position_inner_holder__action_inner__position_run(self):
        self.destruction_position_position_inner_holder__action_inner__position_run.destroy_particle()
