"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.inner


class Middle(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.inner.Inner,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class MiddleExecution:
    def __init__(
        self,
        action: Middle,
        scheduler: literal.Scheduler,
    ):
        self.action = action
        self.scheduler = scheduler
        self.execution_action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_position_action_inner__position_trigger_pos: literal.Position
        self.execution_action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.scheduler,
        )

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_action_inner__position_trigger_pos)
        self.execution_action_inner.on_action_parent_occupied()

    def create_action_inner__position_trigger_pos(self):
        self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_action_inner__position_trigger_pos = self.action.on_particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_action_inner__position_trigger_pos.destroy_particle()
