"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.child


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<run>",
                    constraints=(
                        local.my_domain_com.my_lib.child.Child,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.position_run = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_keeper = literal.LocalPosition(
            "position<keeper>",
            scheduler=self.scheduler,
        )
        self.destruction_position_position_run__global_position_child: literal.Position
        self.join_for_move_position_run__global_position_child_to_position_keeper: literal.Join
        self.join_for_destroy_position_run: literal.Join
        self.join_for_empty_rule_position_run__global_position_child: literal.Join
        self.join_for_empty_rule_position_run: literal.Join

    def accept_for_empty_rule_position_run__global_position_child(self):
        if not self.join_for_empty_rule_position_run__global_position_child.arrive():
            return
        self.move_position_run__global_position_child_to_position_keeper()

    def accept_for_empty_rule_position_run(self):
        if not self.join_for_empty_rule_position_run.arrive():
            return
        self.destroy_position_run()

    def move_position_run__global_position_child_to_position_keeper(self):
        if not self.join_for_move_position_run__global_position_child_to_position_keeper.arrive():
            return
        self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        ).move_particle_to(self.local_position_keeper)
        self.local_position_keeper.move_particle_to(
            self.action.get_interface_position(
                "position<run>"
            ).particle.get_position(
                local.my_domain_com.my_lib.child.Child
            )
        )
        self.destruction_position_position_run__global_position_child = self.action.get_interface_position(
            "position<run>"
        ).particle.get_position(
            local.my_domain_com.my_lib.child.Child
        )
        self.scheduler.submit(self.destroy_position_run)
        self.destroy_position_run__global_position_child()

    def destroy_position_run(self):
        if not self.join_for_destroy_position_run.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_run)

    def continue_destroy_position_run(self):
        self.action.get_interface_position(
            "position<run>"
        ).destroy_particle()
        self.guarantees.position_run.publish(
            self.scheduler,
        )

    def destroy_position_run__global_position_child(self):
        literal.continue_destruction(self.continue_destroy_position_run__global_position_child)

    def continue_destroy_position_run__global_position_child(self):
        self.destruction_position_position_run__global_position_child.destroy_particle()
