"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.fifth_destructor
import local.my_domain_com.my_lib.first_destructor
import local.my_domain_com.my_lib.fourth
import local.my_domain_com.my_lib.fourth_destructor
import local.my_domain_com.my_lib.second
import local.my_domain_com.my_lib.second_destructor
import local.my_domain_com.my_lib.third_destructor


class Destroyer(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<target>",
                    constraints=(
                        local.my_domain_com.my_lib.first_destructor.FirstDestructor,
                        local.my_domain_com.my_lib.second.Second,
                        local.my_domain_com.my_lib.second_destructor.SecondDestructor,
                        local.my_domain_com.my_lib.third_destructor.ThirdDestructor,
                        local.my_domain_com.my_lib.fourth.Fourth,
                        local.my_domain_com.my_lib.fourth_destructor.FourthDestructor,
                        local.my_domain_com.my_lib.fifth_destructor.FifthDestructor,
                    ),
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class DestroyerGuarantees:
    def __init__(self):
        self.position_target = literal.Guarantee()


@final
class DestroyerExecution:
    def __init__(
        self,
        action: Destroyer,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = DestroyerGuarantees()
        self.destruction_connections = destruction_connections
        self.execution_position_target__action_first_destructor: local.my_domain_com.my_lib.first_destructor.FirstDestructorExecution
        self.execution_position_target__action_second_destructor: local.my_domain_com.my_lib.second_destructor.SecondDestructorExecution
        self.execution_position_target__action_third_destructor: local.my_domain_com.my_lib.third_destructor.ThirdDestructorExecution
        self.execution_position_target__action_fourth_destructor: local.my_domain_com.my_lib.fourth_destructor.FourthDestructorExecution
        self.execution_position_target__action_fifth_destructor: local.my_domain_com.my_lib.fifth_destructor.FifthDestructorExecution
        self.destruction_position_position_target__global_position_second: literal.Position
        self.destruction_position_position_target__global_position_fourth: literal.Position
        self.join_for_destroy_position_target: literal.Join
        self.join_for_empty_rule_position_target: literal.Join

    def accept_when_empty_position_target__global_position_second(self):
        self.create_position_target__global_position_second()

    def accept_when_empty_position_target__global_position_fourth(self):
        self.create_position_target__global_position_fourth()

    def accept_when_empty_position_target__global_position_first(self):
        self.execution_position_target__action_first_destructor.accept_when_empty_global_position_first()

    def accept_when_empty_position_target__global_position_third(self):
        self.execution_position_target__action_third_destructor.accept_when_empty_global_position_third()

    def accept_when_empty_position_target__global_position_fifth(self):
        self.execution_position_target__action_fifth_destructor.accept_when_empty_global_position_fifth()

    def accept_when_empty_position_target__global_position_marker(self):
        self.execution_position_target__action_first_destructor.accept_when_empty_global_position_marker()

    def accept_for_empty_rule_position_target(self):
        if not self.join_for_empty_rule_position_target.arrive():
            return
        self.destroy_position_target()

    def init_when_occupied_position_target(self):
        self.execution_position_target__action_first_destructor = local.my_domain_com.my_lib.first_destructor.FirstDestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.first_destructor.FirstDestructor
            ),
            self.scheduler,
        )
        self.execution_position_target__action_first_destructor.guarantees.global_position_first.consumers.append(
            self.destroy_position_target
        )
        self.execution_position_target__action_first_destructor.guarantees.global_position_marker.consumers.append(
            self.accept_guarantee_position_target__action_second_destructor
        )
        self.execution_position_target__action_second_destructor = local.my_domain_com.my_lib.second_destructor.SecondDestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.second_destructor.SecondDestructor
            ),
            self.scheduler,
        )
        self.execution_position_target__action_second_destructor.join_for_empty_rule_global_position_second = literal.NO_JOIN
        self.execution_position_target__action_second_destructor.join_for_move_global_position_second_to_position_holder = literal.NO_JOIN
        self.execution_position_target__action_second_destructor.guarantees.global_position_second.inits.append(
            self.init_position_target__action_second_destructor__global_position_second
        )
        self.execution_position_target__action_second_destructor.guarantees.global_position_second.consumers.append(
            self.destroy_position_target
        )
        self.execution_position_target__action_second_destructor.guarantees.global_position_second.consumers.append(
            self.destroy_position_target__global_position_second
        )
        self.execution_position_target__action_second_destructor.guarantees.global_position_marker.consumers.append(
            self.accept_guarantee_position_target__action_third_destructor
        )
        self.execution_position_target__action_third_destructor = local.my_domain_com.my_lib.third_destructor.ThirdDestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.third_destructor.ThirdDestructor
            ),
            self.scheduler,
        )
        self.execution_position_target__action_third_destructor.guarantees.global_position_third.consumers.append(
            self.destroy_position_target
        )
        self.execution_position_target__action_third_destructor.guarantees.global_position_marker.consumers.append(
            self.accept_guarantee_position_target__action_fourth_destructor
        )
        self.execution_position_target__action_fourth_destructor = local.my_domain_com.my_lib.fourth_destructor.FourthDestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.fourth_destructor.FourthDestructor
            ),
            self.scheduler,
        )
        self.execution_position_target__action_fourth_destructor.join_for_empty_rule_global_position_fourth = literal.NO_JOIN
        self.execution_position_target__action_fourth_destructor.join_for_move_global_position_fourth_to_position_holder = literal.NO_JOIN
        self.execution_position_target__action_fourth_destructor.guarantees.global_position_fourth.inits.append(
            self.init_position_target__action_fourth_destructor__global_position_fourth
        )
        self.execution_position_target__action_fourth_destructor.guarantees.global_position_fourth.consumers.append(
            self.destroy_position_target
        )
        self.execution_position_target__action_fourth_destructor.guarantees.global_position_fourth.consumers.append(
            self.destroy_position_target__global_position_fourth
        )
        self.execution_position_target__action_fourth_destructor.guarantees.global_position_marker.consumers.append(
            self.accept_guarantee_position_target__action_fifth_destructor
        )
        self.execution_position_target__action_fifth_destructor = local.my_domain_com.my_lib.fifth_destructor.FifthDestructorExecution(
            self.action.get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.fifth_destructor.FifthDestructor
            ),
            self.scheduler,
        )
        self.execution_position_target__action_fifth_destructor.guarantees.global_position_fifth.consumers.append(
            self.destroy_position_target
        )
        self.execution_position_target__action_fifth_destructor.guarantees.global_position_marker.consumers.append(
            self.destroy_position_target
        )

    def create_position_target__global_position_second(self):
        self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.second.Second
        ).create_particle()
        self.execution_position_target__action_second_destructor.accept_for_empty_rule_global_position_second()

    def create_position_target__global_position_fourth(self):
        self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.fourth.Fourth
        ).create_particle()
        self.execution_position_target__action_fourth_destructor.accept_for_empty_rule_global_position_fourth()

    def destroy_position_target(self):
        if not self.join_for_destroy_position_target.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_target)

    def continue_destroy_position_target(self):
        self.action.get_interface_position(
            "position<target>"
        ).destroy_particle()
        self.guarantees.position_target.publish(
            self.scheduler,
        )

    def destroy_position_target__global_position_second(self):
        literal.continue_destruction(self.continue_destroy_position_target__global_position_second)

    def continue_destroy_position_target__global_position_second(self):
        self.destruction_position_position_target__global_position_second.destroy_particle()

    def destroy_position_target__global_position_fourth(self):
        literal.continue_destruction(self.continue_destroy_position_target__global_position_fourth)

    def continue_destroy_position_target__global_position_fourth(self):
        self.destruction_position_position_target__global_position_fourth.destroy_particle()

    def init_position_target__action_second_destructor__global_position_second(self):
        self.destruction_position_position_target__global_position_second = self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.second.Second
        )

    def init_position_target__action_fourth_destructor__global_position_fourth(self):
        self.destruction_position_position_target__global_position_fourth = self.action.get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.fourth.Fourth
        )

    def accept_guarantee_position_target__action_second_destructor(self):
        self.execution_position_target__action_second_destructor.accept_when_empty_global_position_marker()

    def accept_guarantee_position_target__action_third_destructor(self):
        self.execution_position_target__action_third_destructor.accept_when_empty_global_position_marker()

    def accept_guarantee_position_target__action_fourth_destructor(self):
        self.execution_position_target__action_fourth_destructor.accept_when_empty_global_position_marker()

    def accept_guarantee_position_target__action_fifth_destructor(self):
        self.execution_position_target__action_fifth_destructor.accept_when_empty_global_position_marker()
