"""Generated by the Define compiler."""

from typing import ClassVar, final

from define.runtime import literal

import local.my_domain_com.my_lib.implied


class Filler(literal.Action):
    implied_qualities: ClassVar[tuple[type[literal.Quality], ...]] = (
        local.my_domain_com.my_lib.implied.Implied,
    )

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class FillerGuarantees:
    def __init__(self):
        self.global_position_implied = literal.Guarantee()
        self.position_trigger_pos = literal.Guarantee()


@final
class FillerExecution:
    def __init__(
        self,
        action: Filler,
        scheduler: literal.Scheduler,
        caller_execution: object | None,
        action_name: str,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.trace_execution = scheduler.execution_created(
            caller_execution,
            action_name,
        )
        self.guarantees = FillerGuarantees()
        self.destruction_connections = destruction_connections
        self.join_for_destroy_position_trigger_pos: literal.Join
        self.join_for_empty_rule_position_trigger_pos: literal.Join

    def accept_when_empty_global_position_implied(self):
        self.create_global_position_implied()

    def accept_for_empty_rule_position_trigger_pos(self):
        if not self.join_for_empty_rule_position_trigger_pos.arrive():
            return
        self.destroy_position_trigger_pos()

    def create_global_position_implied(self):
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.implied.Implied
        ).create_particle()
        self.scheduler.create_completed(
            self.trace_execution,
            "/implied",
            1,
        )
        self.action.on_particle.get_position(
            local.my_domain_com.my_lib.implied.Implied
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "/implied",
            1,
        )
        self.guarantees.global_position_implied.publish(
            self.scheduler,
        )

    def destroy_position_trigger_pos(self):
        if not self.join_for_destroy_position_trigger_pos.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_trigger_pos)

    def continue_destroy_position_trigger_pos(self):
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.scheduler.destroy_completed(
            self.trace_execution,
            "trigger_pos",
            1,
        )
        self.guarantees.position_trigger_pos.publish(
            self.scheduler,
        )
