"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.destroyer
import local.my_domain_com.my_lib.extra_destructor
import local.my_domain_com.my_lib.known_destructor
import local.my_domain_com.my_lib.marker


class CallerB(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class CallerBGuarantees:
    def __init__(self):
        self.position_trigger_pos = literal.Guarantee()


@final
class CallerBExecution:
    def __init__(
        self,
        action: CallerB,
        scheduler: literal.Scheduler,
        *,
        destruction_connections: literal.DestructionConnections | None = None,
    ):
        self.action = action
        self.scheduler = scheduler
        self.guarantees = CallerBGuarantees()
        self.destruction_connections = destruction_connections
        self.local_position_destroyer_particle = literal.LocalPosition(
            "position<destroyer_particle>",
            constraints=(
                local.my_domain_com.my_lib.destroyer.Destroyer,
            ),
            scheduler=self.scheduler,
        )
        self.local_position_carrier = literal.LocalPosition(
            "position<carrier>",
            constraints=(
                local.my_domain_com.my_lib.marker.Marker,
                local.my_domain_com.my_lib.extra_destructor.ExtraDestructor,
                local.my_domain_com.my_lib.known_destructor.KnownDestructor,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_destroyer_particle__action_destroyer: local.my_domain_com.my_lib.destroyer.DestroyerExecution
        self.destruction_connection_position_destroyer_particle__action_destroyer: literal.DestructionConnection
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_extra_destructor: local.my_domain_com.my_lib.extra_destructor.ExtraDestructorExecution
        self.destruction_position_position_destroyer_particle__action_destroyer__position_target__global_position_marker: literal.Position
        self.destruction_position_position_destroyer_particle__action_destroyer__position_trigger_pos: literal.Position
        self.join_for_move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target = self.scheduler.create_join(2)
        self.join_for_destroy_position_destroyer_particle__action_destroyer__position_target__global_position_marker = self.scheduler.create_join(2)
        self.join_for_destroy_position_trigger_pos: literal.Join
        self.join_for_destroy_position_destroyer_particle = self.scheduler.create_join(2)
        self.join_for_empty_rule_position_trigger_pos: literal.Join

    def on_action_parent_occupied(self):
        self.scheduler.submit(self.create_position_destroyer_particle)
        self.create_position_carrier()

    def accept_for_empty_rule_position_trigger_pos(self):
        if not self.join_for_empty_rule_position_trigger_pos.arrive():
            return
        self.destroy_position_trigger_pos()

    def create_position_destroyer_particle(self):
        self.local_position_destroyer_particle.create_particle()
        self.destruction_connection_position_destroyer_particle__action_destroyer = literal.DestructionConnection(
            self.scheduler,
            1,
            self.destroy_position_destroyer_particle__action_destroyer__position_target__global_position_marker,
        )
        self.execution_position_destroyer_particle__action_destroyer = local.my_domain_com.my_lib.destroyer.DestroyerExecution(
            self.local_position_destroyer_particle.particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ),
            self.scheduler,
            destruction_connections=literal.DestructionConnections(
            {
                local.my_domain_com.my_lib.destroyer.DestroyerExecution.continue_destroy_position_target: self.destruction_connection_position_destroyer_particle__action_destroyer,
            },
            ),
        )
        self.execution_position_destroyer_particle__action_destroyer.join_for_empty_rule_position_target__global_position_marker = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer.join_for_empty_rule_position_target = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer.join_for_destroy_position_target = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer.guarantees.position_target.consumers.append(
            self.destroy_position_destroyer_particle
        )
        self.scheduler.submit(self.move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target)
        self.create_position_destroyer_particle__action_destroyer__position_trigger_pos()

    def create_position_carrier(self):
        self.local_position_carrier.create_particle()
        self.local_position_carrier.particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        ).create_particle()
        self.move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target()

    def move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target(self):
        if not self.join_for_move_position_carrier_to_position_destroyer_particle__action_destroyer__position_target.arrive():
            return
        self.local_position_carrier.move_particle_to(
            self.local_position_destroyer_particle.particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            )
        )
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_extra_destructor = local.my_domain_com.my_lib.extra_destructor.ExtraDestructorExecution(
            self.local_position_destroyer_particle.particle.get_action(
                local.my_domain_com.my_lib.destroyer.Destroyer
            ).get_interface_position(
                "position<target>"
            ).particle.get_action(
                local.my_domain_com.my_lib.extra_destructor.ExtraDestructor
            ),
            self.scheduler,
        )
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_extra_destructor.join_for_empty_rule_global_position_marker = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_extra_destructor.join_for_move_global_position_marker_to_position_holder = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_extra_destructor.guarantees.global_position_marker.consumers.append(
            self.destroy_position_destroyer_particle__action_destroyer__position_target__global_position_marker
        )
        self.execution_position_destroyer_particle__action_destroyer.init_position_target__action_known_destructor()
        self.execution_position_destroyer_particle__action_destroyer.execution_position_target__action_known_destructor.join_for_empty_rule_global_position_marker = literal.NO_JOIN
        self.execution_position_destroyer_particle__action_destroyer.execution_position_target__action_known_destructor.join_for_move_global_position_marker_to_position_holder = literal.NO_JOIN
        self.scheduler.submit(self.execution_position_destroyer_particle__action_destroyer.accept_for_empty_rule_position_target__global_position_marker)
        self.execution_position_destroyer_particle__action_destroyer__position_target__action_extra_destructor.accept_for_empty_rule_global_position_marker()

    def create_position_destroyer_particle__action_destroyer__position_trigger_pos(self):
        self.local_position_destroyer_particle.particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_destroyer_particle__action_destroyer__position_trigger_pos = self.local_position_destroyer_particle.particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.scheduler.submit(self.destroy_position_destroyer_particle)
        self.destroy_position_destroyer_particle__action_destroyer__position_trigger_pos()

    def destroy_position_destroyer_particle__action_destroyer__position_target__global_position_marker(self):
        if not self.join_for_destroy_position_destroyer_particle__action_destroyer__position_target__global_position_marker.arrive():
            return
        self.destruction_position_position_destroyer_particle__action_destroyer__position_target__global_position_marker = self.local_position_destroyer_particle.particle.get_action(
            local.my_domain_com.my_lib.destroyer.Destroyer
        ).get_interface_position(
            "position<target>"
        ).particle.get_position(
            local.my_domain_com.my_lib.marker.Marker
        )
        self.destruction_position_position_destroyer_particle__action_destroyer__position_target__global_position_marker.destroy_particle()
        self.destruction_connection_position_destroyer_particle__action_destroyer.complete()

    def destroy_position_trigger_pos(self):
        if not self.join_for_destroy_position_trigger_pos.arrive():
            return
        literal.continue_destruction(self.continue_destroy_position_trigger_pos)

    def continue_destroy_position_trigger_pos(self):
        self.action.get_interface_position(
            "position<trigger_pos>"
        ).destroy_particle()
        self.guarantees.position_trigger_pos.publish(
            self.scheduler,
        )

    def destroy_position_destroyer_particle(self):
        if not self.join_for_destroy_position_destroyer_particle.arrive():
            return
        self.local_position_destroyer_particle.destroy_particle()

    def destroy_position_destroyer_particle__action_destroyer__position_trigger_pos(self):
        self.destruction_position_position_destroyer_particle__action_destroyer__position_trigger_pos.destroy_particle()
