"""Generated by the Define compiler."""

from typing import final

from define.runtime import literal

import local.my_domain_com.my_lib.inner


class First(literal.Action):

    def __init__(self, on_particle: literal.Particle):
        super().__init__(
            on_particle,
            interface_positions=[
                literal.LocalPosition(
                    "position<trigger_pos>",
                    scheduler=on_particle.scheduler,
                ),
            ],
        )


@final
class FirstExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.inner.Inner,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_inner: local.my_domain_com.my_lib.inner.InnerExecution
        self.destruction_position_position_box__action_inner__position_trigger_pos: literal.Position

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_inner = local.my_domain_com.my_lib.inner.InnerExecution(
            self.scheduler,
        )
        self.scheduler.submit(self.create_position_box__action_inner__position_trigger_pos)
        self.execution_position_box__action_inner.on_action_parent_occupied()

    def create_position_box__action_inner__position_trigger_pos(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_box__action_inner__position_trigger_pos = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.inner.Inner
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_box__action_inner__position_trigger_pos.destroy_particle()
        self.local_position_box.destroy_particle()
