"""Generated by the Define compiler."""

from typing import final, override

from define.runtime import literal

import local.my_domain_com.my_lib.a
import local.my_domain_com.my_lib.holder
import local.my_domain_com.my_lib.middle


class Test(literal.EntryPoint):

    @override
    def execute(self, scheduler: literal.Scheduler):
        execution = TestExecution(
            scheduler,
        )
        execution.on_action_parent_occupied()


@final
class TestExecution:
    def __init__(
        self,
        scheduler: literal.Scheduler,
    ):
        self.scheduler = scheduler
        self.local_position_box = literal.LocalPosition(
            "position<box>",
            constraints=(
                local.my_domain_com.my_lib.middle.Middle,
            ),
            scheduler=self.scheduler,
        )
        self.execution_position_box__action_middle: local.my_domain_com.my_lib.middle.MiddleExecution
        self.destruction_position_position_box__action_middle__position_gw: literal.Position
        self.destruction_position_position_box__action_middle__position_gw__global_position_holder: literal.Position
        self.destruction_position_position_box__action_middle__position_gw__global_position_holder__global_position_a: literal.Position
        self.destruction_position_position_box__action_middle__position_trigger_pos: literal.Position
        self.join_for_destroy_position_box = self.scheduler.create_join(2)

    def on_action_parent_occupied(self):
        self.create_position_box()

    def create_position_box(self):
        self.local_position_box.create_particle()
        self.execution_position_box__action_middle = local.my_domain_com.my_lib.middle.MiddleExecution(
            self.local_position_box.particle.get_action(
                local.my_domain_com.my_lib.middle.Middle
            ),
            self.scheduler,
        )
        self.execution_position_box__action_middle.join_for_empty_rule_position_gw__global_position_holder__global_position_a = literal.NO_JOIN
        self.execution_position_box__action_middle.join_for_destroy_position_gw__global_position_holder__global_position_a = literal.NO_JOIN
        self.scheduler.submit(self.create_position_box__action_middle__position_gw)
        self.create_position_box__action_middle__position_trigger_pos()

    def create_position_box__action_middle__position_gw(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gw>"
        ).create_particle()
        self.execution_position_box__action_middle.init_when_occupied_position_gw()
        self.execution_position_box__action_middle.execution_position_gw__action_inner.guarantees.global_position_holder__global_position_a.inits.append(
            self.init_position_box__action_middle__position_gw__action_inner__global_position_holder__global_position_a
        )
        self.execution_position_box__action_middle.execution_position_gw__action_inner.guarantees.global_position_holder__global_position_a.consumers.append(
            self.destroy_position_box__action_middle__position_gw
        )
        self.execution_position_box__action_middle.execution_position_gw__action_inner.guarantees.global_position_holder__global_position_a.consumers.append(
            self.destroy_position_box__action_middle__position_gw__global_position_holder
        )
        self.execution_position_box__action_middle.execution_position_gw__action_inner.guarantees.global_position_holder__global_position_a.consumers.append(
            self.destroy_position_box__action_middle__position_gw__global_position_holder__global_position_a
        )
        self.scheduler.submit(self.create_position_box__action_middle__position_gw__global_position_holder)
        self.execution_position_box__action_middle.continue_when_occupied_position_gw()

    def create_position_box__action_middle__position_gw__global_position_holder(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gw>"
        ).particle.get_position(
            local.my_domain_com.my_lib.holder.Holder
        ).create_particle()
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gw>"
        ).particle.get_position(
            local.my_domain_com.my_lib.holder.Holder
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        ).create_particle()
        self.execution_position_box__action_middle.accept_for_empty_rule_position_gw__global_position_holder__global_position_a()

    def create_position_box__action_middle__position_trigger_pos(self):
        self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        ).create_particle()
        self.destruction_position_position_box__action_middle__position_trigger_pos = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<trigger_pos>"
        )
        self.destruction_position_position_box__action_middle__position_trigger_pos.destroy_particle()
        self.destroy_position_box()

    def destroy_position_box__action_middle__position_gw(self):
        self.destruction_position_position_box__action_middle__position_gw.destroy_particle()
        self.destroy_position_box()

    def destroy_position_box__action_middle__position_gw__global_position_holder(self):
        self.destruction_position_position_box__action_middle__position_gw__global_position_holder.destroy_particle()

    def destroy_position_box__action_middle__position_gw__global_position_holder__global_position_a(self):
        self.destruction_position_position_box__action_middle__position_gw__global_position_holder__global_position_a.destroy_particle()

    def destroy_position_box(self):
        if not self.join_for_destroy_position_box.arrive():
            return
        self.local_position_box.destroy_particle()

    def init_position_box__action_middle__position_gw__action_inner__global_position_holder__global_position_a(self):
        self.destruction_position_position_box__action_middle__position_gw = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gw>"
        )
        self.destruction_position_position_box__action_middle__position_gw__global_position_holder = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gw>"
        ).particle.get_position(
            local.my_domain_com.my_lib.holder.Holder
        )
        self.destruction_position_position_box__action_middle__position_gw__global_position_holder__global_position_a = self.local_position_box.particle.get_action(
            local.my_domain_com.my_lib.middle.Middle
        ).get_interface_position(
            "position<gw>"
        ).particle.get_position(
            local.my_domain_com.my_lib.holder.Holder
        ).particle.get_position(
            local.my_domain_com.my_lib.a.A
        )
